# Contrato del NAMESPACE.
#
# `api/NAMESPACE` se genera con `roxygen2::roxygenise("api")` y `DESCRIPTION`
# fija `Roxygen: list(roclets = c("namespace"))` para que esa corrida no
# produzca `api/man/`. El archivo estuvo desincronizado mucho tiempo: 181
# funciones con `@export` nunca llegaron al NAMESPACE, dos métodos S3 no
# estaban registrados y `importFrom(magrittr,"%>%")` vivía editado a mano
# dentro del bloque «generated by roxygen2» (cualquier regeneración lo
# borraba y rompía los usos de `%>%`).
#
# Este test es el gate contra esa deriva. No corre roxygen (tardaría minutos):
# compara los tags `@export` del código fuente contra el NAMESPACE con un
# parser propio, así el desfase se ve en la suite normal.

.ns_dir_r <- function() testthat::test_path("..", "..", "R")
.ns_path <- function() testthat::test_path("..", "..", "NAMESPACE")

# Nombre del objeto que sigue a un bloque roxygen: primera línea no-roxygen y
# no-vacía con forma `nombre <- ` (admite backticks y comillas).
.ns_objeto_tras_bloque <- function(lineas, desde) {
  for (j in seq(desde, length(lineas))) {
    linea <- lineas[[j]]
    if (grepl("^\\s*#'", linea)) next
    if (grepl("^\\s*$", linea)) next
    if (grepl("^\\s*#", linea)) next
    # Clases POSIX a propósito: en el motor TRE de R, `\\s` dentro de `[...]`
    # no es la clase de espacio, es el literal backslash-s.
    m <- regmatches(
      linea,
      regexec(
        "^[[:space:]]*[`\"']?([^[:space:]`\"'<=]+)[`\"']?[[:space:]]*(<-|=)[[:space:]]*",
        linea
      )
    )[[1]]
    if (length(m) >= 2) return(m[[2]])
    return(NA_character_)
  }
  NA_character_
}

# Todos los nombres con `#' @export` en api/R/*.R.
.ns_exports_declarados <- function() {
  archivos <- list.files(.ns_dir_r(), pattern = "\\.R$", full.names = TRUE)
  out <- list()
  for (archivo in archivos) {
    lineas <- readLines(archivo, warn = FALSE)
    idx <- which(grepl("^\\s*#'\\s*@export\\s*$", lineas))
    for (i in idx) {
      nombre <- .ns_objeto_tras_bloque(lineas, i + 1L)
      if (!is.na(nombre)) {
        out[[length(out) + 1L]] <- list(nombre = nombre, archivo = basename(archivo))
      }
    }
  }
  out
}

# Nombres que el NAMESPACE deja alcanzables: export() directo y el nombre
# completo `generico.clase` de cada S3method().
.ns_namespace_nombres <- function() {
  lineas <- readLines(.ns_path(), warn = FALSE)
  exportados <- regmatches(lineas, regexec("^export\\((.+)\\)\\s*$", lineas))
  exportados <- vapply(
    Filter(function(x) length(x) >= 2, exportados),
    function(x) gsub("^[`\"']|[`\"']$", "", x[[2]]),
    character(1)
  )
  s3 <- regmatches(lineas, regexec("^S3method\\(([^,]+),(.+)\\)\\s*$", lineas))
  s3 <- vapply(
    Filter(function(x) length(x) >= 3, s3),
    function(x) paste0(gsub("^[`\"']|[`\"']$", "", x[[2]]), ".",
                       gsub("^[`\"']|[`\"']$", "", x[[3]])),
    character(1)
  )
  list(exportados = exportados, alcanzables = c(exportados, s3))
}

test_that("todo `@export` del código está en el NAMESPACE", {
  declarados <- .ns_exports_declarados()
  expect_gt(length(declarados), 300)

  ns <- .ns_namespace_nombres()
  nombres <- vapply(declarados, function(x) x$nombre, character(1))
  faltantes <- declarados[!nombres %in% ns$alcanzables]

  detalle <- vapply(
    faltantes,
    function(x) paste0(x$nombre, " (", x$archivo, ")"),
    character(1)
  )
  expect_equal(
    detalle, character(0),
    info = paste0(
      "Hay `@export` sin línea en api/NAMESPACE. Regenerá con ",
      "`Rscript -e 'roxygen2::roxygenise(\"api\")'`, no agregues la línea a mano."
    )
  )
})

test_that("todo export del NAMESPACE tiene su `@export` en el código", {
  ns <- .ns_namespace_nombres()
  declarados <- vapply(.ns_exports_declarados(), function(x) x$nombre, character(1))
  huerfanos <- setdiff(ns$exportados, declarados)

  expect_equal(
    huerfanos, character(0),
    info = paste0(
      "Hay export() en api/NAMESPACE sin `@export` en el código: son líneas ",
      "editadas a mano que la próxima regeneración va a borrar."
    )
  )
})

test_that("ningún nombre exportado empieza con punto", {
  # Convención de la casa: `.nombre` es interno y se alcanza con `:::`.
  # `.mapear_etiquetas`, `.resolver_datos_multitabla` y
  # `.validacion_resolve_repeat_children` llegaron a exportarse por un
  # `@export` de más; ninguno se usa fuera del namespace.
  ns <- .ns_namespace_nombres()
  expect_equal(grep("^\\.", ns$exportados, value = TRUE), character(0))
})

test_that("el NAMESPACE importa el pipe de magrittr", {
  # 13 archivos usan `%>%` sin declararlo en su propio roxygen; el
  # `@importFrom` vive en api/R/prosecnurapp-package.R. Si ese archivo
  # desaparece, roxygen borra el import y el paquete deja de instalar.
  lineas <- readLines(.ns_path(), warn = FALSE)
  expect_true(any(grepl('^importFrom\\(magrittr,"%>%"\\)$', lineas)))
})
