// Notas de versión de Prosecnur — ubicación canónica.
//
// Se muestran en Configuración → Novedades (GlobalSettingsDialog) y en el
// ReleaseNotesDrawer del Home; el BootGate chooser reusa el mismo diálogo
// vía ChooserSettings. La entrada más reciente va PRIMERO.

export type ReleaseNote = {
  version: string;
  date: string;
  highlights: string[];
};

export const RELEASE_NOTES: ReleaseNote[] = [
  {
    version: "0.8.0",
    date: "2026-08-24",
    highlights: [
      "Cálculo de muestra: cada facultad dimensiona con su propia tasa de efectividad. Antes un solo divisor global servía para las quince, y ahora cada facultad publica la suya con los dos factores que la componen; la certificación suma las encuestas esperadas aula por aula y declara con qué método las estimó.",
      "Cálculo de muestra: la selección se certifica en alumnos garantizados por facultad, no en aulas contadas. La tarjeta trae las cuotas de hombre y de mujer por celda, y el balance de sexo se publica facultad por facultad en barras pareadas de cuota contra oferta.",
      "Cálculo de muestra: Coincidencia compara la selección nueva contra lo que el estudio anterior aplicó de verdad, no contra lo que planeó. El embudo comparado pone la diferencia al frente y se abre por facultad.",
      "Cálculo de muestra: construir el marco deja de congelar la app. Los trabajos largos dicen lo que van a tardar antes de lanzarse, siguen corriendo si sales de la vista, y la app los retoma donde estaban al volver.",
      "Cálculo de muestra: una facultad puede quedar exenta de un criterio general. Cada ficha dice qué criterios rigen solo ahí, y las facultades excluidas se declaran en lugar de deducirse de la tabla.",
      "Cálculo de muestra: la cuenta del dimensionamiento se abre por facultad y responde por qué salen 203 aulas y no 170. La distribución de elegibles por aula se dibuja, así que el estadístico con el que se dimensiona se ve en vez de citarse.",
      "Cálculo de muestra: un mismo docente deja de salir repetido entre titulares, y los intercambios que eso provoca quedan registrados a la vista.",
      "Cálculo de muestra: Variables dice qué columna está usando el motor para cada rol y se confirma de un clic. También nombra las columnas que el archivo ya no tiene, en vez de resolverlas en silencio.",
      "Cálculo de muestra: el marco se lee cuando el encabezado viene desplazado, que es como lo emite el formato de la DTI.",
      "Cálculo de muestra: el sorteo balanceado da la misma muestra en cualquier máquina cuando la matriz de balance tiene rango completo. Sobre una matriz de rango deficiente sigue sin ser reproducible entre plataformas, y mientras eso siga abierto una selección se reproduce partiendo del plan guardado en el proyecto.",
      "Monitoreo de aulas: el avance se mide contra la cuota del diseño y no contra la suma de las metas por aula. Las dos cifras conviven con rótulos distintos, porque una dice si el estudio se cumple y la otra dirige el campo; medir con la segunda subestimaba el cumplimiento y un estrato podía no llegar nunca al 100 % con su cuota cubierta.",
      "Monitoreo de aulas: la agenda se recorre día por día y por facultad, y el acumulado dice cuándo se llega a la meta con su proyección punteada. Cada sexo se proyecta sobre lo agendado y declara cuándo alcanza su propia cuota.",
      "Monitoreo de aulas: el libro operativo entra como fuente y se lee también desde una pestaña de Google Sheets. Sale con portada, desplegables, cabecera y panel congelado, y distingue lo que trae la app de lo que llena la persona en campo.",
      "Monitoreo de aulas: el descuadre del parte de campo se ve al escribirlo y no al importarlo, y el control de identificadores personales dejó de dar siempre el mismo resultado.",
      "Monitoreo de aulas: el banco de extras dice si alcanza para cubrir la cuota, no solo cuántas aulas tiene. El colchón de reservas se abre facultad por facultad y un reemplazo se activa desde el registro de campo.",
      "Monitoreo: las señales de calidad de campo separan lo que sigue produciendo daño de lo que ya terminó de producirlo. Solo el formulario desactualizado avisa fuerte, porque cada hora que pasa cuesta otra encuesta perdida; nombres mal escritos o encuestas superpuestas son hechos ya ocurridos e informan sin frenar el campo.",
      "Recopiladores: la ficha de campo dice lo que el aplicador necesita para saber que está en el aula correcta, y pide los cuatro números del cuadre. El paquete se reparte por facultad y por rol en vez de salir como un PDF combinado.",
      "Recopiladores: el plan avisa cuando viene de un sorteo distinto del vigente, y ofrece rehacerlo con el coste por delante.",
      "Limpieza: la base depurada se promueve y llega al entregable. Antes quedaba como descarga recomendada que ningún consumidor leía, y dos casos excluidos con decisión y justificación reaparecieron en el entregable de un estudio ya cerrado.",
      "Validación: apagar una regla o dejar una variable fuera de la auditoría exige decir por qué. El informe metodológico declara de cuántas a cuántas encuestas va y qué preguntas no cubre el plan.",
      "Codificación: «no categorizar» se registra como decisión con su motivo. Decidir no categorizar una variable por casos insuficientes no tenía dónde vivir y se confundía con un olvido; ahora la lista distingue los cuatro estados y cuenta lo que sigue pendiente.",
      "Gráficos: cada gráfico se denomina sobre quien pudo responder la pregunta, no sobre la muestra entera.",
      "Gráficos: el redondeo y los decimales se configuran por tipo de gráfico, y el informe declara cómo redondea. El 0,5 sube siempre, así que un mismo empate deja de subir o bajar según la paridad del número vecino.",
      "PowerPoint: las tablas salen nativas del programa, con color por fila para armar la leyenda de la escala.",
      "Tu proyecto guarda ahora solo lo que decidiste, no una copia de los valores de fábrica. Un mazo puede verse distinto tras actualizar la app: las mejoras de estilo llegan a los proyectos existentes en vez de quedar tapadas por la copia del día en que se guardaron. Lo que sí elegiste se conserva.",
      "Gráficos: una sola regla de negrita para todos los tipos de gráfico. Van en negrita el título, el subtítulo y las cifras; el resto queda apagado y se enciende cuando hace falta. Antes cada tipo traía su propio juego y un mazo con nueve tipos se leía como nueve mazos.",
      "Gráficos: siete interruptores de negrita que no cambiaban nada ahora funcionan. El título del boxplot, el subtítulo de las barras agrupadas y los títulos de bloque de las multiapiladas estaban fijos en el motor aunque la casilla existiera.",
      "Gráficos: en las láminas de perfil, cada gráfico dice sobre cuántos casos habla. Antes una sola línea al pie servía para los cuatro paneles aunque midieran públicos distintos: la lámina de personal administrativo daba 15 casos a tres gráficos y 52 al cuarto.",
      "Gráficos: numerar los grupos usa la palabra de tu estudio. Escribes «OE», «Dimensión» o «Eje» y el motor antepone la numeración; antes solo sabía escribir «OE» y a veces la ponía sin que nadie la pidiera.",
      "Gráficos: el ancho de las columnas de una lámina que compara varios públicos se edita. El enunciado del bloque, el nombre del público y la barra extra tienen su medida, y las barras se ajustan con lo que quede.",
      "Gráficos: el texto de la lámina de Objetivo ya no sale girado en PowerPoint.",
      "Gráficos: el Top 2 Box se declara por nombre de categoría y deja de deducirse del orden de la escala. La regla anterior sumaba las dos últimas columnas dando por hecho que la escala iba de peor a mejor; cuando no lo era, sumaba las dos equivocadas sin decir nada. Si hoy no hay categorías declaradas, la columna se omite y el motor avisa por qué.",
      "Gráficos: las categorías del Top 2 Box se marcan sobre las escalas reales del estudio. El selector fusiona las escalas idénticas, cabe en el panel e ignora mayúsculas y tildes al emparejar, así que «De acuerdo» y «DE ACUERDO» son la misma categoría.",
      "Gráficos: el Top 2 Box compara contra la medición anterior. La lámina muestra el valor de hoy junto al de la ola previa, que es la lectura que pide un informe de acreditación.",
      "Gráficos: el estilo de acreditación se enciende desde la interfaz. La paleta se ancla a la etiqueta real de cada categoría y los cortes del semáforo se editan sin salir de la vista.",
      "Gráficos: buscador de ajustes en la base visual y en el inspector de cada lámina. Encuentra escribiendo sin tildes y solo cuenta los ajustes que de verdad puede mostrar.",
      "Gráficos: el orden manual de barras se reordena arrastrando, no tecleando. La lista ofrece la escala de esa pregunta en vez de las 23 del estudio, y el orden guardado llega al motor además de al proyecto.",
      "Gráficos: los arreglos que el motor aplica solo llegan al analista. Antes corregía en silencio y la lámina salía distinta de lo pedido sin que constara en ninguna parte; los avisos repetidos se agrupan en vez de inundar la pantalla.",
      "Gráficos: el recorte de enunciados deja de ser silencioso, y el aviso lleva al control que lo resuelve.",
      "Gráficos: cinco tipos nuevos en el catálogo: serie temporal, divergentes, dumbbell, lollipop y puntos comparativos. Las barras agrupadas y las apiladas con cruce marcan las diferencias significativas.",
      "Gráficos: el texto usa el azul de la marca en los ocho motores. Barras agrupadas ya lo hacía y los otros siete pintaban en negro puro, que era el segundo color más usado del mazo medido.",
      "Gráficos: la leyenda de dos filas reparte parejo, deja de pisarse en multilista y ya no reserva el doble de la banda que dibuja.",
      "Gráficos: ranuras con nombre para colores e íconos, tomadas de las secciones del estudio en lugar de una lista fija. Cada campo pide el dato que espera recibir.",
      "Gráficos: el editor de espacios habla en las medidas de la lámina y no en las del motor.",
      "Cálculo de muestra: el Relato cuenta la selección escena por escena, del marco al sorteo. Cada cuadro es un hecho de la corrida ejecutada, así que la selección se puede defender mostrando el proceso y no solo la tabla final.",
      "Cálculo de muestra: la probabilidad publicada es la del sorteo que realmente ocurrió. Tres configuraciones publicaban la del diseño nominal, y con esa cifra se ponderaba todo lo que viniera después.",
      "Cálculo de muestra: el dimensionamiento responde si el marco alcanza, en vez de apuntar siempre al centro del rango.",
      "Cálculo de muestra: el mapa de selección dice quién dicta cada curso-horario y muestra sus nombres legibles.",
      "Cálculo de muestra: los ids de alumno se subrogan al guardar en lugar de borrarse. Sin ellos no había traslape que descontar, así que al reabrir un proyecto la siguiente selección corría sin descontar repetidos. Del proyecto guardado se lee que dos aulas comparten siete alumnos; no se puede nombrar a ninguno.",
      "Formularios: una base queda ligada a la revisión publicada de su instrumento en cualquier vía de carga, no solo en acreditación. El bloqueo de publicación dice qué hacer y separa los avisos de los impedimentos reales.",
      "Word: la columna extra recupera su piso y el bloque de multilista conserva la exclusión de opciones. Una batería que excluía «Sin información» la recuperaba al exportar, y el porcentaje cambiaba entre la pantalla y el documento.",
      "Proyecto: guardar avisa de lo que no pudo viajar dentro del proyecto.",
    ],
  },
  {
    version: "0.7.1",
    date: "2026-08-05",
    highlights: [
      "Cálculo de muestra · Histórico: la pestaña se recorre por desglose. Seis vistas que se ofrecen solo si hay datos para responderlas: el embudo, por facultad, por criterio, semana a semana, titulares y reemplazos, y cómo se dimensionó. Antes era una pila de 2.800 píxeles donde las comparaciones que importan quedaban a media pantalla de distancia.",
      "Cálculo de muestra · Histórico: el embudo declara todo lo que pierde en cada paso. Un peldaño bajaba de 4.425 a 3.303 y la leyenda explicaba solo 335 de esas 1.122 personas; ahora se nombran las dos mermas y el tramo de quienes respondieron sin aparecer en el conteo del aula, así que las cifras cierran.",
      "Cálculo de muestra · Histórico: una fila por curso-horario titular con la historia de su cadena. Cada columna es un escalón: verde con la cifra de encuestas y la efectividad del aula, ámbar con la letra del motivo por el que se cayó, gris para los suplentes que nunca hizo falta contactar. Agrupada por facultad y ordenada por lo que costó.",
      "Cálculo de muestra · Histórico: semana a semana con sus cifras absolutas. Cada semana declara a cuántos alcanzaba, cuántos faltaron, cuántos ya habían contestado y cuántas encuestas salieron, y cada porcentaje lleva al lado las dos cantidades que lo producen.",
      "Cálculo de muestra · Histórico: la composición del marco por criterio, cruzada con facultad. Cada barra reparte las aulas de una facultad entre las categorías del criterio, con la paleta categórica del sistema y un separador entre tramos.",
      "Cálculo de muestra · Histórico: cumplimiento de cuota por facultad y sexo. Es cumplimiento y no efectividad —el denominador es la cuota del diseño, no una población—, así que puede pasar del 100 %. Con esto queda a la vista qué facultad no llegó y por qué hubo que ponderarla.",
      "Cálculo de muestra · Histórico: «Cómo se dimensionó» recorre de la población entera a la base con la que se analizó, con los casos recortados y dónde hizo falta ponderar. Antes era una lista de parámetros sueltos que terminaba en las aulas.",
      "Cálculo de muestra: la base histórica declara su propio diseño. El formato es un libro de tres hojas —referencia por curso-horario, diseño con las cifras del estudio y cuotas por facultad— y es el mismo para leer y para publicar.",
      "Cálculo de muestra: los tramos de tamaño salen de los grupos que declara el estudio en Marco. Si no los usa, la dimensión no se dibuja en vez de imponer una escala del motor.",
      "Cálculo de muestra · Selección: nueva pestaña con el perfil de la muestra. De qué está hecha, facultad por facultad: cuántas aulas y cuántos elegibles, y qué tipo de cursos-horario le tocó a cada una, con el marco vigente como referencia.",
      "Cálculo de muestra: los gráficos tienen su propio hover. El del navegador tardaba casi un segundo, se pintaba con la tipografía del sistema y aplanaba en una línea un dato con título y cuatro cifras.",
      "Cálculo de muestra · Explorador de bases: describe las bases tal como se leyeron, por facultad y no solo en total, dibuja hasta cuarenta categorías con la cola desplegable y traduce también los valores que calcula el marco.",
      "Cálculo de muestra: el histórico se lee en un proyecto que no declara grupos de tamaño. El backend devolvía el dato entero y el cliente lo descartaba en silencio, así que la pestaña quedaba en blanco sin decir por qué.",
      "Cálculo de muestra: un campo ausente viaja como nulo y no como objeto vacío. Un estudio sin diseño previo declarado mandaba diecisiete campos que el cliente no sabía leer, y eso invalidaba toda la lectura.",
      "Cálculo de muestra · Explorador de bases: da salida cuando la población no viaja en el proyecto guardado, en vez de mandar a buscar un problema que no existe.",
      "Carga · Equivalencias: nueva pestaña donde el estudio declara qué pregunta de un público es la misma que la de otro. Comparar públicos dependía de recordar que la variable `p13_1` de docentes es la `p11_1` de estudiantes, y el error no daba ninguna señal: en el mazo medido, un grupo comparaba «¿Conoce…?» de docentes contra «¿Ha utilizado…?» de estudiantes, 90 % contra 31 %. Las etiquetas de la matriz aterrizan en la configuración de cada base.",
      "Carga · Equivalencias: el emparejamiento se hace en pantalla. Una fila por pregunta con los públicos en paralelo, propuestas por etiqueta, escala y orden de aparición que se ven como propuestas y se confirman de un clic, y el Excel queda como import y export. Una propuesta sin confirmar no se guarda, y una variable no puede estar en dos filas.",
      "Carga · Equivalencias: la plantilla empieza por lo que hay que decidir —sección, etiqueta estándar y una columna por público— y deja detrás el plan del informe. Antes emitía una fila por variable de cada base, 300 en el estudio medido, y alinearlas exigía cortar y pegar hasta que los códigos calzaran.",
      "Analítica: las etiquetas curadas pertenecen a su base y no al estudio. En un estudio de bases separadas los overrides se aplican por nombre de variable, así que una etiqueta escrita mirando una base se aplicaba a las demás, donde ese nombre designa otra pregunta: con diez etiquetas editadas salían seis variables mal rotuladas en estudiantes y nueve en administrativos. Gráficos usa las mismas etiquetas por base.",
      "Gráficos · Equivalencias: el radar compara públicos. Un eje por tema y una línea por base del estudio, con un indicador que declaras tú —«Sí», o la suma de «De acuerdo» y «Totalmente de acuerdo»—. Ninguno de los radares del motor podía tener una serie por fuente: cruzaban por una variable dentro de una base.",
      "Gráficos · Equivalencias: el estilo del radar se declara por bloque. Comparativo, silueta, auditoría o limpio, porque una batería de perfil se presenta con líneas y una de diagnóstico con la grilla a la vista, y las dos conviven en el mismo mazo.",
      "Gráficos: el radar arranca el eje en la mitad alta. Un indicador de acuerdo vive entre 90 % y 98 %, y de 0 a 100 las tres series se dibujan una encima de otra. Si un tema cae por debajo del piso, el motor lo baja solo y lo dice.",
      "Gráficos: la forma la decide cuántos actores hay. Con un solo público el eje es la pregunta y el actor se dice una vez en el pie; el canal lateral del tema existe para separar dos dimensiones, y repetir «Administrativos» en las siete barras no informa nada.",
      "Gráficos: el top-two-box sale encendido cuando la escala lo admite. La columna extra ya salía de fábrica, pero con 3 pt de tamaño, sin título y sin color: ocupaba el sitio y no decía nada.",
      "Gráficos: la escala de acuerdo va de rojo a verde pasando por un durazno, y una dicotomía usa dos tonos del mismo azul. El azul marino en el extremo positivo es el color de la marca y no el de «lo mejor»; el rojo contra azul marcaba una de las dos opciones como mala.",
      "Gráficos: la lámina usa el alto que tiene. El lienzo se armaba con 3,56 pulgadas para un hueco de 6 y el 41 % quedaba en blanco, con la leyenda cobrando un fijo de 0,75 para dibujar una línea de texto. Una barra sigue midiendo lo mismo en toda la presentación (ADR 0065).",
      "Gráficos: los títulos de bloque dejan de escribirse unos encima de otros. Con enunciados completos como nombre de tema, tres bloques seguidos se apilaban y la columna izquierda quedaba ilegible.",
      "Gráficos · Equivalencias: la lámina se titula con su sección cuando la matriz no declara enunciado. El relleno automático usaba el rótulo de la primera variable, que nombra un tema y no la diapositiva: tres láminas seguidas salían «Servicio de salud» siendo cosas distintas.",
      "Gráficos · Equivalencias: los nombres de columna de la tabla se editan con una caja por base, y el editor ya no ofrece un radar que el mazo va a rechazar por nombres de tema largos.",
      "Gráficos: nueve láminas salían sin nota de base. El camino de escalas mixtas exigía referencias de varias fuentes para emitirla; en un informe de encuesta la base no es opcional.",
      "Gráficos: un gráfico cuyo indicador principal es el porcentaje muestra solo el porcentaje. El conteo pegado a la cifra —«45% (9)»— pasa a ser opción apagada de fábrica: la nota de Base ya declara el N de la lámina, así que repetirlo en cada barra competía con la cifra que importa.",
      "Gráficos · Indicador numérico: la tarjeta dice qué estadístico muestra. La métrica viajaba declarada de tres formas distintas —«N» en el constructor, «mean» en la interfaz y `mean()` cableado en el motor—, así que el valor por defecto declarado nunca fue el efectivo. Ninguna cifra existente cambia.",
      "Gráficos: una barra corta vuelve a existir en la lámina. El umbral que decide si la etiqueta va dentro o fuera comparaba contra una escala de proporciones, la etiqueta externa heredaba el color interno —blanca sobre blanca— y, ya visible, chocaba con el N de encima.",
      "Gráficos: el eje de categóricas habla en porcentajes, no en proporciones crudas, y el título del eje del histograma deja de escribirse encima de sus propias marcas.",
      "Gráficos · Histograma: los intervalos no inventan cortes que no existen. Sobre una variable entera, pedir un número de tramos producía rangos como «19-22,5» y al redondear repetía el límite.",
      "Gráficos · Equivalencias: «la misma escala» se define una sola vez. La matriz normalizaba la etiqueta —minúsculas y espacios colapsados, porque la caja de una opción es un accidente de transcripción del cuestionario— y Gráficos usaba la etiqueta cruda, así que el mazo derivado agrupaba dos variables en un bloque y el validador acto seguido declaraba que no comparten escala: 30 errores sobre 44 láminas que bloqueaban el export de un mazo que el motor renderiza sin tocar nada. La etiqueta que se lee sigue siendo la del cuestionario.",
      "Gráficos · Word: el documento alcanza la paridad editorial de la presentación. Las etiquetas y la leyenda se calibran al ancho real del Word en vez de heredar el lienzo de la diapositiva —una barra sola dejaba seis pulgadas de vacío y baja a 2,96—, el título, el gráfico y la nota de Base viajan juntos sin partirse de página, el panel multiactor escala con cuántos actores hay y la columna extra que la lámina pedía deja de apagarse al exportar.",
    ],
  },
  {
    version: "0.7.0",
    date: "2026-08-04",
    highlights: [
      "Gráficos: el índice del reporte se arma por secciones. Cada sección lleva su título, sus subtemas y un ícono elegido de un catálogo de diez; antes eran cuatro cajas de texto con nombres internos y los focos salían con íconos fijos.",
      "Gráficos: el selector de paletas entiende los estudios de varias bases. Dice en qué bases vive cada lista, agrupa las listas con las mismas opciones y aplica una paleta a todo el grupo de una vez, con vuelta atrás; los colores elegidos llegan idénticos al reporte.",
      "Gráficos: comparar públicos por tema funciona con todas las bases del estudio. Escalas iguales escritas con mayúsculas distintas, o con una categoría residual de más, se leen como una sola serie, con leyenda única y el Top 2 calculado sobre las categorías reales.",
      "Gráficos: la Base de cada lámina vive en la esquina inferior izquierda del slide. El caption dentro del gráfico queda como opción, las láminas con varios gráficos suman las bases de todos los actores y la leyenda ya no pisa el texto de Base.",
      "Gráficos: el export termina aunque el plan tenga láminas a medio armar. Una lámina sin gráfico sale con su título y el lienzo vacío, y mezclar tipos de lámina ya no rompe la lectura del plan.",
      "Gráficos: las barras salen bien puestas por defecto. Una apilada de una sola fila es una banda con cuerpo y centrada, los porcentajes chicos viven dentro de su segmento sin flechas de desborde, y la lámina automática de «Otros» se enciende solo si se pide.",
      "Formularios: duplicar o guardar un proyecto conserva los instrumentos del editor y el plan de gráficos. El guardado espera los cambios de los últimos segundos, y una carga fallida ya no deja un plan vacío en su lugar.",
    ],
  },
  {
    version: "0.6.3",
    date: "2026-08-03",
    highlights: [
      "Carga: un estudio que organiza varias bases lo sigue haciendo al reabrirlo. La declaración vivía mientras la pantalla estaba montada y se perdía al cerrar el proyecto, así que Fuentes volvía a mostrar «Plan pendiente de activar» y desaparecía el camino a las bases siguientes. Los proyectos anteriores abren como hasta ahora.",
      "Carga: la mesa de bases separadas deja siempre un carril libre para la siguiente base. Al reabrir un proyecto la única base ocupaba el único carril y no quedaba dónde subir otra; la salida era subir «Entradas previstas», y no estaba a la vista. El tope lo sigue poniendo el estudio.",
      "Formularios: el panel que arma la fórmula de una variable calculada cabe en el ancho que tiene. Las filas de condición pedían más espacio del disponible, el control del valor quedaba cortado contra el borde y el nombre técnico de la pregunta se leía «$_».",
      "Formularios: una variable que resume muchas preguntas se lee sin repetirlas. Los grupos que comparan la misma pregunta la enuncian una vez y listan sus criterios debajo, la fórmula «si… entonces… si no» aparece como tres pasos, y una franja arriba dice cuántas condiciones hay y qué valores devuelve. Un índice de 21 preguntas baja un 22 % de alto.",
      "Cálculo de muestra: cada criterio de curso-horario enseña sobre qué decide. Densidad, caja y cuantiles sobre una escala común a todas las categorías del criterio, con sus cursos-horario totales, los elegibles, los alumnos únicos y la asistencia previa cuando el marco la trae. Antes se elegía contra una cifra suelta.",
      "Cálculo de muestra: el recorrido se sigue criterio a criterio. Antes de cada uno dice cuántos cursos-horario llegan y qué porcentaje del universo son; al final, con cuántos te quedas. Había una sola línea a media lista que anunciaba el resultado final en mitad del camino.",
      "Cálculo de muestra: confirmar un criterio actualiza el recorrido sin reconstruir la población. El botón de calcular queda para lo que de verdad toca las dos dimensiones, y el aviso dice cuál de las dos se quedó atrás en vez de pedir un recálculo entero. Al abrir un proyecto guardado hace falta reconstruir una vez: el recálculo por criterio necesita el marco de esta sesión.",
      "Cálculo de muestra: «Descartar» devuelve el criterio a su valor confirmado. Solo lo hacía con las categorías; el rango de niveles, el mínimo por facultad, la tasa y las exclusiones apagaban el aviso y dejaban el cambio puesto, así que el borrador seguía sucio y se descubría al recalcular.",
      "Cálculo de muestra: la composición del curso-horario dice qué cuesta cada porcentaje. El deslizador anuncia cuántos cursos-horario descarta en esa posición y con qué porcentaje del total te quedas, y su distribución se lee sobre 0–100 % porque describe la composición, no el número de alumnos. Sus tres reglas comparten la tarjeta estándar del resto de criterios.",
      "Cálculo de muestra: las categorías con más cursos-horario van primero, en todas las superficies que las listan. Salían en el orden de la columna de origen, así que la categoría que se lleva la mitad del marco podía quedar quinta. El orden lo fijan los cursos-horario que la categoría tiene, no los que siguen incluidos, para que la lista no se reordene bajo el cursor al conmutar.",
      "Cálculo de muestra: el nivel del curso se acota con un rango de dos manijas. Eran dos listas desplegables que en un marco real ofrecían 852 opciones cada una. Además, los criterios se pliegan uno a uno o todos a la vez, y la tabla de criterios por facultad se recorre con teclado.",
    ],
  },
  {
    version: "0.6.2",
    date: "2026-08-01",
    highlights: [
      "Monitoreo telefónico: una hoja de barrido que trae varios actores en una sola columna vuelve a repartir el universo entre ellos. Antes no atribuía las filas a ninguno y los dos actores quedaban en universo 0.",
      "Monitoreo telefónico: el botón Avance vuelve a leer las hojas de Google. Se caían del refresco, así que el barrido quedaba sin actualizar y el estudio entero se mostraba sin base, con universo 0 y brechas «S/M», igual que uno recién conectado.",
      "Monitoreo telefónico: las metas de cuota se escriben completas y se confirman al final. Cada tecla guardaba y recalculaba, de modo que teclear «80» dejaba sedimentado el «8» del camino y borrar el campo lo devolvía a 0. Ahora los cambios se acumulan en un borrador, una franja dice cuántos esperan confirmación, y el recálculo ocurre una sola vez. Descartar vuelve a lo guardado.",
      "Monitoreo telefónico: el equipo se cuenta por personas y no por asignaciones, tanto en los estados por encuestador como en las tarjetas de producción. Quien cubría dos componentes aparecía dos veces, así que un equipo de cuatro se reportaba como ocho y una carga pareja de 46, 46, 45 y 46 se leía como 40 y 6. Los porcentajes se recalculan sobre los totales de cada persona, no se promedian entre sus filas.",
      "Fuentes: el catálogo de formularios de Kobo consulta el servidor de la cuenta conectada. Con una cuenta en servidor propio el token viajaba al servidor público y volvía un error de credenciales, cuando lo que estaba mal era la dirección.",
    ],
  },
  {
    version: "0.6.1",
    date: "2026-08-01",
    highlights: [
      "Monitoreo: un estudio recién abierto conecta sus fuentes desde el primer día. La pantalla de Fuentes exigía un corte ya sincronizado, y el corte sale justamente de sincronizar: un proyecto nuevo veía «0/3 · Sin corte» y un panel vacío en el lugar del botón de conectar. Las pantallas sin datos traen ahora la cifra de este proyecto y la puerta a donde se resuelve.",
      "Editor de formularios: un nombre de formulario o una ruta de exportación sin espacios deja de salirse de su caja. El conmutador recorta el nombre largo y lo muestra completo al posar el cursor, y el detalle del aviso quiebra la ruta dentro de la ventana.",
    ],
  },
  {
    version: "0.6.0",
    date: "2026-07-31",
    highlights: [
      "Bitácora: el estudio se dibuja en un lienzo espacial. Colocas nodos, los conectas y despliegas sus ramas sin salir del lienzo, con deshacer y rehacer. Los nodos apuntan a piezas reales de la app, a hitos o a entradas de la bitácora, y el mapa completo se exporta e importa.",
      "Bitácora: el cronograma del estudio se arma por fases dentro de la app, y un centro de avisos reúne las alertas sin interrumpir el trabajo.",
      "Navegación: toda vista tiene dirección propia y se comparte. Cada pantalla, panel y pestaña queda descrita en la barra de direcciones, así que un enlace lleva exactamente a donde estabas. Al abrir un proyecto aterrizas en su propio inicio, nunca en una pantalla heredada de otro estudio.",
      "Monitoreo territorial: declaras a mano qué columna de tu base corresponde a cada variable, en la primera pestaña de UMPs. Antes se adivinaba sola y podía errar en silencio, eligiendo una columna vacía o una parecida pero distinta, con cifras creíbles y equivocadas como resultado. Cada variable muestra ahora su porcentaje de datos y un ejemplo real.",
      "Monitoreo: las fuentes se ordenan por la pregunta que responden (qué se recoge, con qué actores y por dónde entra) y no por el servicio técnico de origen. El ritmo diario muestra en qué terminó cada llamada, el embudo se lee en Avance y un caso completo que no cruza aparece primero, porque es lo que hay que rescatar.",
      "Recopiladores: módulo nuevo para preparar la salida a campo, con plan de recolección, accesos, materiales, entrega y ficha de encuestador con código QR.",
      "Cálculo de muestra: el Marco separa el total de elegibles del promedio por curso-horario y nombra cada cifra por lo que es. Antes podían leerse como conteo de personas.",
      "Rendimiento: la app abre más rápido, porque las comprobaciones de arranque y los proyectos recientes se resuelven en paralelo. Monitoreo conserva sus reportes dentro del proyecto en vez de recalcularlos y cancela las consultas al cambiar de pantalla. Importar desde SurveyMonkey o Kobo ya no congela la interfaz.",
      "Legibilidad: los nombres de distrito, responsable y base dejan de recortarse. El texto de Monitoreo telefónico recupera sus tildes, las barras de insistencia vuelven a sumar 100%, un avance sin meta declarada deja de mostrarse como 0% y los errores de Kobo que puedes resolver tú se explican como tales.",
    ],
  },
  {
    version: "0.5.19",
    date: "2026-07-24",
    highlights: [
      "Gráficos (crítico): el reporte PPT de estudios con varias bases (madre y grupos repetibles) vuelve a generarse. Todas las láminas fallaban con un error de «current_code». Ahora sale completo, con cada servicio graficado por separado y las láminas de la madre sobre su total. Si una lámina no encuentra los datos de un filtro, queda en blanco en vez de tumbar el reporte.",
      "Codificación (crítico): aplicar la codificación de una base en un estudio multibase ya no borra su catálogo de grupos. Antes la base quedaba marcada como codificada pero perdía todas sus definiciones editables. Complementa el arreglo de la 0.5.18, que cubría el mismo problema al volver a limpiar.",
      "Codificación: en preguntas de selección múltiple asignas una misma respuesta a varias categorías a la vez. Cada respuesta muestra sus categorías como etiquetas de color, y el menú deja marcar varias sin cerrarse.",
      "Codificación: tras aplicar, la pantalla muestra solo las preguntas reales del instrumento. Antes ofrecía las variables recodificadas como si fueran preguntas por codificar.",
      "Libro de códigos (crítico): vuelve a generarse en PDF cuando alguna variable no trae etiqueta. Antes fallaba con «subscript out of bounds».",
      "Entregables: las recodificaciones se resaltan por tipo (opción única, selección múltiple o rangos numéricos) en el libro de códigos, el instrumento y la base exportada, con un interruptor para activarlo.",
      "Reportes ACNUR: las etiquetas de categoría se alinean a la derecha, pegadas a sus barras, y la línea de base queda más limpia («Base: 427 de 430 (99.3%)»). El logo PULSO acompaña al de ACNUR también en las láminas de sección, y el informe grafica solo preguntas del instrumento, dejando fuera campos de control como el consentimiento. El libro de códigos aplica el mismo criterio.",
    ],
  },
  {
    version: "0.5.18",
    date: "2026-07-22",
    highlights: [
      "Codificación: volver a limpiar o ajustar una base ya codificada conserva tu trabajo. Antes, re-finalizar la limpieza eliminaba en silencio todo el catálogo de grupos; ahora solo queda marcada para volver a aplicarse con un clic, con las definiciones intactas.",
    ],
  },
  {
    version: "0.5.17",
    date: "2026-07-22",
    highlights: [
      "Gráficos: el reporte de estudios con grupos repetibles (por ejemplo, varios servicios atendidos por una misma persona) vuelve a generarse cuando las bases están codificadas, y cada servicio se grafica con sus respuestas recodificadas.",
      "Procesamiento: cada base usa su propia versión de los datos, codificada si ya la aplicaste y original si no. Las recodificaciones de una base se reflejan en los reportes sin necesidad de codificar todas las del estudio.",
    ],
  },
  {
    version: "0.5.16",
    date: "2026-07-22",
    highlights: [
      "Editor de formularios: abres los instrumentos guardados en el proyecto desde una instalación nueva, otra computadora o una sesión sin caché local.",
      "Editor de formularios: recupera instrumentos que no incluyen la hoja opcional de diagnóstico, sin obligarte a importarlos de nuevo.",
      "Editor de formularios: distingue una publicación bloqueada de la posibilidad de abrir y seguir editando el instrumento.",
      "Editor de formularios: muestra la primera observación que impide publicar y cuántas quedan pendientes.",
    ],
  },
  {
    version: "0.5.15",
    date: "2026-07-22",
    highlights: [
      "Gráficos: los grupos repetibles se abren por servicio, con una sección por servicio, titulada con su nombre y con su propia base de respuestas. Antes se mezclaban en un solo gráfico.",
      "Gráficos: avisa cuando hay recodificaciones definidas sin aplicar, o desfasadas del catálogo, así el reporte no muestra las categorías originales por error.",
      "Gráficos: el informe consolidado guarda su avance solo y comparte el mismo alcance entre variables, cobertura y vista previa. El plan sugerido se genera más rápido.",
      "Carga: estrena el ingreso multiactor de acreditación con un catálogo de actores del estudio, y la importación de bases SAV con revisión de la normalización antes de incorporarlas.",
      "Editor de formularios: registra el origen SurveyMonkey de cada formulario y asigna actores, para trazar de dónde viene cada instrumento.",
      "Reportes PPT: las barras Sí/No se ven más llenas y equilibradas, y las láminas de sección se diferencian con tipografía y un acento propio. Se renueva el acceso a los planes predeterminados junto con el diálogo de estilo global.",
      "Correcciones: el informe de gráficos incluye todas las bases del estudio y no solo la del grupo repetible. Validación mantiene consistentes las preguntas de opción múltiple al reconstruir la base, y abrir pantallas de solo lectura deja de marcar el proyecto como editado.",
    ],
  },
  {
    version: "0.5.14",
    date: "2026-07-21",
    highlights: [
      "Editor de formularios: publicas revisiones del cuestionario que quedan fijas y confirman su lógica, así el resto del flujo sabe qué versión del instrumento se acreditó. Cada formulario muestra su estado de publicación y se abre desde un enlace.",
      "Carga y Procesamiento: estrenan el flujo de acreditación de formularios. Promueve por lote los registros efectivos ya reconciliados desde Monitoreo y da a cada base su propio ingreso a Procesamiento, con una aprobación metodológica antes de habilitarla.",
      "Analítica y Validación: alinean solas sus fuentes y reglas con la revisión del formulario acreditado, así el análisis y los controles trabajan sobre el instrumento correcto.",
      "Gráficos: estrena el informe consolidado multibase, que reúne en un documento las bases hermanas aprobadas con leyendas que identifican a cada actor, y suma un resumen de respondientes por variable.",
      "Validación: el reporte metodológico territorial muestra el embudo de filtrado de válidos, cuadra el universo por una llave común y detalla los registros válidos con más claridad.",
      "Correcciones: Validación reconoce las opciones Sí/No sin importar mayúsculas ni el prefijo del grupo, y Limpieza exporta a Excel las tablas del motor de decisiones sin fallar.",
    ],
  },
  {
    version: "0.5.13",
    date: "2026-07-20",
    highlights: [
      "Codificación: asignas un mismo texto a varias categorías en una sola revisión, también en estudios multibase y grupos repetibles.",
      "Gráficos y reportes: personalizas el título de portada para ACNUR, y la ficha técnica gana una cabecera más clara y mayor detalle territorial.",
      "Codificación: relacionas preguntas desde un selector, sin arrastrarlas, con una edición de relaciones más clara y accesible.",
      "Navegación: recorres las pestañas deslizantes con las flechas, Inicio y Fin, para trabajar desde el teclado.",
      "Cálculo de muestra: compara cada distribución con una escala propia y evita cruces incorrectos entre valores homónimos de distintos tipos de sesión.",
    ],
  },
  {
    version: "0.5.12",
    date: "2026-07-17",
    highlights: [
      "Apariencia: Prosecnur estrena su identidad visual definitiva, con isotipo canónico, familia de logos y un lenguaje visual unificado en toda la app. El ícono oficial aparece en el Dock, la barra de tareas y el instalador.",
      "Apariencia: los módulos comparten un mismo marco, con banda de indicadores canónica, interruptores uniformes y acentos de color propios de cada módulo. El panel de pestañas de tercer nivel se muestra siempre compacto, con la pestaña activa resaltada.",
      "Cálculo de muestra: el diseño del marco se reorganiza «todo por facultad», un embudo que va de lo general a lo particular donde cada facultad decide sus propios criterios. Incluye una radiografía de estudiantes elegibles y aulas sobrevivientes, detalle por tipo de sesión (rango, mediana y media) y selección manual de los cursos-horario finales.",
      "Editor de formularios: estrena la vista «Filtros de opciones», con un diagrama de las relaciones entre listas, y exporta el XLSForm ya depurado. Las matrices de una sola pregunta se incluyen en el PDF cuando tú lo decides.",
      "Entregables: suma la ficha técnica territorial ACNUR en dos láminas, el reporte del formulario en PDF y Word fiel al modelo 2026, y un libro relacional que reúne la base madre y sus grupos repetibles en un solo Excel.",
      "Procesamiento: aplica la codificación por base en estudios multibase y prioriza las etiquetas del instrumento en las salidas de Analítica. En Gráficos, los colores que eliges por serie se conservan con exactitud en la vista previa y en la exportación.",
      "Monitoreo y Carga: el avance telefónico cuenta respuestas efectivas en lugar de contactos, el corte para el cliente aplica las correcciones y exclusiones registradas en Carga, y el filtro de universo suma reglas de exclusión que quedan documentadas en el reporte metodológico.",
    ],
  },
  {
    version: "0.5.11",
    date: "2026-07-15",
    highlights: [
      "Carga: marcas a mano qué registros pertenecen al universo real del estudio, dejando fuera pruebas y piloto. El filtro se materializa por base y las tablas repeat lo heredan solas.",
      "Validación: genera un reporte metodológico completo del plan aplicado, con qué evalúa cada regla, sobre qué universo y con qué resultado, listo para anexar al informe del estudio.",
      "Validación: suma controles operacionales sobre las reglas del instrumento, con manejo explícito de duplicados y rangos de fecha con zona horaria.",
      "Monitoreo: agrega el PDF de avance telefónico para el cliente, con resumen del campo, ritmo diario y estado de cuotas.",
      "Editor de formularios: exporta el cuestionario a Word con la misma composición del PDF, y el hub de formularios muestra conteos reales de preguntas y secciones.",
      "Cálculo de muestra: nuevo método estadístico para estudiantes por aula con límite inferior conservador (bootstrap al 95%), seleccionable desde la pestaña de cursos-horario.",
      "Formulario en PDF: las matrices ganan legibilidad, con etiquetas más anchas, escalas sin rotar cuando caben y filas más compactas.",
    ],
  },
  {
    version: "0.5.10",
    date: "2026-07-15",
    highlights: [
      "Cálculo de muestra: las categorías se muestran tal cual vienen en tu base, sin reetiquetados automáticos.",
      "Cálculo de muestra: la pestaña Variables separa las columnas del estudiante de las del curso-horario, cada una bajo su propia hoja.",
      "Cálculo de muestra: el mapeo de columnas ofrece todos los encabezados disponibles de cada hoja, incluido el tipo de docente.",
      "Inicio: cada tarjeta de módulo muestra en qué punto vas y qué sigue, con las métricas y el acceso directo más relevantes.",
    ],
  },
  {
    version: "0.5.9",
    date: "2026-07-14",
    highlights: [
      "Cálculo de muestra: rediseña la sección de Cálculo con Diseño, parámetros por facultad y cursos-horario por facultad, más una vista de Cobertura con dos gráficos por facultad.",
      "Cálculo de muestra: en Datos puedes mapear las columnas a mano, ver tarjetas por tipo y trabajar hasta dos escenarios de muestra.",
      "Editor de formularios: el editor de texto de las preguntas suma color y encabezados, y el Mapa de lógica se renueva por completo — eliminar relaciones desde el visor, conexiones dibujadas en arco, minimapa para orientarte, contador de relaciones por sección y una leyenda mucho más clara.",
      "Cálculo de muestra: los criterios de elegibilidad traen una selección canónica por defecto, se reconcilian solos al remapear y muestran un inventario de valores únicos en Datos → Consistencia.",
      "Cálculo de muestra: los cálculos largos ahora se pueden cancelar y muestran su estado, con el tiempo del sorteo final acotado.",
      "Cálculo de muestra: corrige la distribución por sexo con estudiantes únicos, el tipo de docente jerárquico y el mapeo de columnas de curso-horario; el aviso de reconstruir aparece solo cuando hay un cambio real.",
      "Procesamiento: la reconstrucción de preguntas de opción múltiple conserva todas las alternativas y reconoce correctamente las columnas marcadas con Sí/No.",
    ],
  },
  {
    version: "0.5.8",
    date: "2026-07-13",
    highlights: [
      "Procesamiento: carga archivos XLSX con varias hojas y las organiza automáticamente en bases relacionadas por grupo repetible.",
      "Analítica: hereda el peso de diseño de la base principal a cada grupo repetible, sin necesidad de ponderar hoja por hoja.",
      "Validación: muestra los conteos por servicio o grupo repetible en un indicador segmentado, para ubicar de un vistazo dónde están los casos.",
      "Cálculo de muestra: mantiene el resumen del diseño siempre visible mientras ajustas los criterios de selección, con confirmación explícita para cada cambio, y hace del mínimo elegible el criterio autoritativo sin filtros redundantes.",
      "Cálculo de muestra: unifica el vocabulario a \"curso-horario\" en todo el recorrido, en monitoreo y en recopiladores, para no confundirlo con el aula física.",
      "Apariencia: las pestañas de toda la aplicación cambian con un indicador animado más fluido.",
      "Instalación Windows: evita reinstalar el motor estadístico en cada arranque y elimina los diálogos de error duplicados.",
    ],
  },
  {
    version: "0.5.7",
    date: "2026-07-13",
    highlights: [
      "Instalación Windows: permite elegir la carpeta donde instalar Prosecnur y conserva esa elección al actualizar.",
      "Instalación Windows: verifica que la ruta seleccionada tenga permisos de escritura antes de copiar archivos.",
      "Instalación Windows: reintenta de forma segura la recuperación del motor estadístico cuando una instalación previa quedó incompleta.",
    ],
  },
  {
    version: "0.5.6",
    date: "2026-07-13",
    highlights: [
      "Inicio: renueva el panel de control y el carrusel de módulos para que cada proyecto muestre sus accesos y avances con mayor claridad.",
      "Procesamiento: hace visible la estructura de grupos repetibles desde Carga, Validación y Analítica, con rosters relacionales que permiten explorar cada base sin perder contexto.",
      "Analítica: conserva etiquetas y el orden del instrumento con más fidelidad, mejora los entregables de grupos repetibles y evita columnas duplicadas o vacías en las bases exportadas.",
      "Validación: incorpora controles de coherencia entre la base principal y sus grupos repetibles, y distingue claramente la base activa al revisar reglas.",
      "Editor de formularios: transforma el mapa de lógica y el lienzo en una experiencia más legible, con búsquedas para listas extensas, relaciones diferenciadas y edición de secciones más directa.",
      "Cálculo de muestra: organiza los criterios por categoría y convierte el marco de aulas en un recorrido más trazable, con embudos y decisiones de diseño fáciles de explicar.",
    ],
  },
  {
    version: "0.5.5",
    date: "2026-07-10",
    highlights: [
      "Inicio: cada proyecto abre en su propio panel de control que resume el avance y la madurez de cada módulo, y el selector de proyectos estrena una presentación unificada más clara y adaptable a la pantalla.",
      "Bitácora: estrena un módulo único que reúne el diseño del estudio y el cronograma, con altas y bajas de actividades y hora en el calendario.",
      "Analítica: suma ponderación con pesos de diseño y raking, con una vista previa que diagnostica el efecto sobre la muestra antes de aplicarla.",
      "Analítica: genera el libro de códigos en PDF de la base final —incluida la base panel— en el orden del formulario y con la orientación código o etiqueta que elijas.",
      "Analítica: permite fijar el orden de las categorías ordinales y lo propaga a frecuencias, cruces, tablas y PPT, con un catálogo de listas y controles por fila.",
      "Analítica: exporta un script de replicación (.R) que reconstruye la base final de forma reproducible.",
      "Procesamiento: soporta formularios con grupos repetibles de punta a punta —ingesta, validación, analítica y entregables.",
      "Carga: trae el trabajo de campo validado desde Monitoreo a Procesamiento en un paso claro, reemplazando la base cruda en su sitio.",
      "Monitoreo: el inicio refleja el avance territorial vivo, el revamp de aulas ordena los indicadores en una banda de KPIs y los enlaces directos abren la sección correcta.",
      "Validación: recupera la pregunta madre de los select_multiple para no marcar falsos positivos, y reconoce validación y plan por base en estudios multibase.",
      "Apariencia: recalibra los controles al UI Kit de macOS y alinea Fichas QR, Cálculo de muestra y otras vistas al lenguaje visual de la suite.",
    ],
  },
  {
    version: "0.5.4",
    date: "2026-07-09",
    highlights: [
      "Cálculo de muestra: reconstruye Muestra de aulas como un recorrido didáctico que explica cada fórmula y decisión del diseño paso a paso.",
      "Cálculo de muestra: corre los cálculos grandes en segundo plano con progreso visible, historial de corridas y un paquete de defensa listo para sustentar el diseño.",
      "Cálculo de muestra: evalúa la salud del diseño — censo, cobertura, balance y precisión — y señala los riesgos por severidad.",
      "Reportes PDF: estrena la estética institucional Pulso en los avances de campo, el libro de códigos a dos columnas con índice y el formulario en papel.",
      "Monitoreo: exporta las UMP con ocurrencias a Excel con filtros listos y asigna el responsable correcto incluso cuando hubo reemplazos.",
      "Validación: avisa cuando una regla apunta a datos que no calzan con la base, antes de generar falsos positivos.",
      "Carga: reconoce las bases que llegan desde Monitoreo y muestra las etiquetas en español de los formularios Kobo.",
    ],
  },
  {
    version: "0.5.3",
    date: "2026-07-07",
    highlights: [
      "Editor de formularios: suma asistentes guiados para saltos, filtros de opciones, validaciones, cálculos y mensajes de campo, sin escribir sintaxis técnica.",
      "Editor de formularios: refuerza el lienzo de lógica, el catálogo de opciones y la restauración del autoguardado.",
      "Monitoreo: agrega la mesa de reconciliación territorial con cola de UMP, ajustes operativos con historial y lentes de revisión.",
      "Procesamiento: compacta la navegación en rieles de íconos y pule las mesas de trabajo de Carga, Validación, Codificación y Analítica.",
      "Gráficos: amplía el selector de modelos, unifica la barra superior y estabiliza la vista previa al cambiar de lámina.",
      "Apariencia: moderniza Home, Carga, Cálculo de muestra, Validación, Codificación y Analítica con el nuevo lenguaje visual de la suite.",
    ],
  },
  {
    version: "0.5.2",
    date: "2026-07-03",
    highlights: [
      "Gráficos: estrena la biblioteca de modelos de láminas, calibrada con la plantilla PPT real del estudio.",
      "Gráficos: genera la vista previa de láminas localmente, lista para funcionar en la app instalada.",
      "Gráficos: aclara la suite de estilo global — presets, modos por espacio y placeholders dinámicos — con vocabulario más simple.",
      "Gráficos: compacta la barra superior, el inspector y el timeline para aprovechar mejor la pantalla.",
      "Gráficos: guía la recuperación de modelos pendientes y muestra la salud del plan antes de exportar.",
    ],
  },
  {
    version: "0.5.1",
    date: "2026-07-02",
    highlights: [
      "Procesamiento: procesa estudios de acreditación con varios actores, cada uno con su propia base Kobo.",
      "Carga: importa bases hermanas independientes desde Kobo dentro del mismo proyecto.",
      "Procesamiento: sugiere los siguientes pasos del pipeline según el diseño del estudio.",
      "Monitoreo: adapta el seguimiento a estudios de acreditación y encuestas telefónicas con perfiles dedicados.",
      "Gráficos: mide la cobertura del plan de láminas para detectar variables aún sin graficar.",
      "Procesamiento: agrega un visor de hojas para revisar la base procesada sin salir de la app.",
    ],
  },
  {
    version: "0.5.0",
    date: "2026-06-30",
    highlights: [
      "Arranque: acelera la apertura de proyectos con precarga en caliente y una pantalla de inicio que muestra el progreso real.",
      "Plan de trabajo: mantiene el cronograma del estudio sincronizado con el avance del proyecto.",
      "Monitoreo: prepara las salidas publicables con indicadores de disponibilidad más confiables y paneles por canal mejor distribuidos.",
      "Calidad: suma proyectos de auditoría reproducibles que respaldan cada versión con evidencia visual.",
    ],
  },
  {
    version: "0.4.0",
    date: "2026-06-22",
    highlights: [
      "Cálculo de muestra: amplía el flujo de marcos, aulas, acreditación y escenarios con persistencia más robusta.",
      "Carga: suma entradas directas desde plataformas, mejor soporte para ZIP/SAV y controles de fuentes multibase.",
      "Codificación y reportes: incorpora importación Excel de categorizaciones y ficha técnica metodológica exportable.",
      "Dashboard, Analítica, Gráficos y Hojas de ruta: consolida mejoras visuales y operativas acumuladas para el nuevo corte.",
      "Monitoreo: este corte mantiene fuera los últimos cambios en desarrollo del módulo.",
    ],
  },
  {
    version: "3.4.2",
    date: "2026-06-18",
    highlights: [
      "Monitoreo: consolida el centro operativo territorial para revisar el avance, las incidencias y las decisiones de campo en un solo recorrido.",
      "Monitoreo: refuerza los reportes publicables con controles de salida antes de compartirlos.",
      "Carga: hace más clara la revisión de fuentes y bases vinculadas al proyecto.",
      "Apariencia: adapta las vistas principales a pantallas compactas y reduce desplazamientos innecesarios.",
    ],
  },
  {
    version: "3.4.1",
    date: "2026-06-17",
    highlights: [
      "Monitoreo: agrega una auditoría territorial por UMP que distingue la asignación declarada de la reconciliada.",
      "Monitoreo: reconstruye las distribuciones de cuota cuando faltan filas de auditoría, para conservar una lectura completa del campo.",
      "Monitoreo: muestra el avance por recopilador en estudios de acreditación.",
      "Carga: permite revisar con mayor detalle los archivos SurveyMonkey recibidos como ZIP SAV antes de incorporarlos.",
    ],
  },
  {
    version: "3.4.0",
    date: "2026-06-17",
    highlights: [
      "Monitoreo: publica reportes agregados como páginas de consulta de solo lectura.",
      "Carga: importa levantamientos SurveyMonkey sin conexión desde libros de trabajo y paquetes ZIP SAV.",
      "Codificación: exporta e importa la configuración de categorías en un archivo reutilizable.",
      "Validación: permite excluir variables que no corresponden al control de calidad del estudio.",
      "Monitoreo: mejora la lectura territorial de los casos y el seguimiento operativo del campo.",
    ],
  },
  {
    version: "3.3.4",
    date: "2026-06-11",
    highlights: [
      "Carga: mantiene la actualizacion incremental SurveyMonkey por fuente principal y campanas/canales persistidos.",
      "Consentimiento: conserva el conteo de registros validos bajo pregunta y opcion aprobatoria.",
      "Monitoreo: ajusta la nomenclatura territorial a registros validos, no validos y casos por revisar.",
      "Monitoreo: pule visualmente los indicadores GPS, duracion y resumen territorial.",
      "Deploy: estabiliza el empaquetado macOS local sin firma/notarizacion automatica.",
    ],
  },
  {
    version: "3.3.3",
    date: "2026-06-11",
    highlights: [
      "Carga: actualiza respuestas SurveyMonkey de bases ya trabajadas sin reemplazar datos locales y reporta registros validos nuevos.",
      "SurveyMonkey multibase: permite agregar campanas/canales a una base existente, persistirlas y refrescarlas junto con la fuente principal.",
      "Consentimiento: muestra la pregunta y opcion aprobatoria que definen los registros validos en Carga/Bases.",
      "Codificacion: conserva el avance y relanza la reaplicacion cuando entran respuestas nuevas.",
      "Monitoreo: incorpora Google Sheets como superficie operativa controlada para publicar salidas Prosecnur sin modificar la hoja viva de campo.",
      "Monitoreo: refuerza taxonomia de estados, consultas internas, fuentes multiples y documentacion arquitectonica del centro operativo.",
    ],
  },
  {
    version: "3.3.2",
    date: "2026-06-09",
    highlights: [
      "Codificación: conserva mejor las recodificaciones y el avance al volver al proyecto.",
      "Analítica: limpia las opciones “Otro” en frecuencias y reportes para presentar resultados más claros.",
      "Gráficos: ordena paletas y categorías según el instrumento y permite decidir cómo mostrar los ceros en barras agrupadas.",
      "Carga: conserva las etiquetas originales al incorporar respuestas desde SurveyMonkey.",
      "Reportes: mejora la composición de gráficos en las salidas de PowerPoint y Word.",
    ],
  },
  {
    version: "3.3.1",
    date: "2026-06-05",
    highlights: [
      "Graficos: muestra el selector de iconos en Contenido para los slides con icono y toma los PNG subidos en Configuracion global.",
      "Graficos: evita que etiquetas o titulos guardados como objetos vacios rompan la pantalla al volver a /graficos.",
      "Graficos: estabiliza titulos automaticos y manuales para que el titulo del grafico se mantenga en preview, PPT y Word.",
      "Editor visual: corrige la X del canvas dinamico para que no compita con separadores ni cambie de icono al hacer click.",
      "Paletas: aplica colores por lista en preview/export y muestra listas de todas las fuentes en proyectos multibase.",
      "Word/PPT: refuerza presets, leyendas y composicion de graficos apilados, agrupados, numericos, pie, radar y reportes Word.",
      "Analitica multibase: mejora la seleccion y recuperacion de bases procesadas para reducir estados incompletos.",
    ],
  },
  {
    version: "0.3.3",
    date: "2026-06-05",
    highlights: [
      "Gráficos: genera títulos automáticos más útiles y conserva los títulos elegidos al volver al plan.",
      "Gráficos: ordena paletas y categorías de acuerdo con el instrumento para mantener consistencia entre láminas.",
      "Gráficos: permite controlar la presencia de categorías con valor cero en las barras agrupadas.",
      "Reportes: mejora la composición de barras apiladas, agrupadas y numéricas en PowerPoint y Word.",
      "Analítica: recupera con mayor estabilidad las bases procesadas en proyectos multibase.",
    ],
  },
  {
    version: "0.3.2",
    date: "2026-06-04",
    highlights: [
      "Hojas de ruta: corrige el layout del PDF integrado para que la tabla de recorrido no se corte ni choque con el pie de pagina.",
      "Revision final: evita que las tablas anchas atrapen el scroll vertical cuando se revisan titulares y reemplazos.",
      "Inspector de zonas: estabiliza las tarjetas de zonas para que viviendas, personas, estado y accion no se superpongan.",
    ],
  },
  {
    version: "0.3.1",
    date: "2026-06-04",
    highlights: [
      "Carga multibase: aplica la logica XLSForm de una base plantilla a hermanas compatibles, incluyendo relevant, constraint, required, choice_filter y calculation.",
      "SurveyMonkey multibase: importa hermanas independientes desde una o varias campañas, con estrategia de recoleccion y exclusiones de validacion por fuente.",
      "Validacion: enmascara reglas por fila/fuente para evitar falsos positivos cuando preguntas administrativas no aplican a fuentes autoadministradas.",
      "Hojas de ruta: separa fases piloto y campo real, refuerza el resumen de fuentes/configuracion y conserva snapshots mas trazables.",
      "Drilldown y visualizacion: mejora la inspeccion de reglas, el panel de detalle y el render Plotly para flujos de validacion mas exigentes.",
      "Graficos: recupera fuentes procesadas validas cuando el cache queda incompleto y evita que listas invalidas lleguen al motor de reportes.",
      "Reportes Word/PPT: usa etiquetas XLSForm como titulos por defecto y limpia sufijos de variables recodificadas en el indice Word.",
      "Documentacion y pruebas: agrega ADR 0009, actualiza arquitectura multibase y suma cobertura R/React para los nuevos contratos.",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-06-02",
    highlights: [
      "Arquitectura canonica: guia principal y ADRs para app local, formato .pulso, secretos fuera del proyecto, modulos por dominio, integraciones salientes y auditoria reproducible.",
      "Auditoria canonica: nuevo proyecto .pulso sintetico, comandos Make y smoke de Electron para diagnosticar regresiones con capturas, sid, puerto y checksum aislados.",
      "Conexiones: Configuracion centraliza SurveyMonkey, Kobo y Google Sheets, guarda credenciales fuera del .pulso, soporta perfiles SurveyMonkey y solo expone mascaras al frontend.",
      "Multibase y monitoreo: mejor importacion de familias SurveyMonkey, bases hermanas independientes, sincronizacion de fuentes, seleccion de base activa y motores mas defensivos.",
      "Home y shell: nuevo deck de modulos, Ajustes con notas/creditos/conexiones, catalogo de modulos compartido y estados de proyecto mas claros.",
      "Calidad del release: mas pruebas frontend/R para cliente API, carga multibase, codificacion, analitica, persistencia .pulso, secretos y auditoria.",
    ],
  },
  {
    version: "0.2.9",
    date: "2026-05-27",
    highlights: [
      "Validación: agrega un recorrido guiado para definir y revisar transformaciones de limpieza.",
      "Validación: fortalece las reglas personalizadas y muestra con mayor claridad cómo se aplican al instrumento.",
      "Editor de formularios: estrena un espacio de trabajo enfocado para editar preguntas y secciones con menos distracciones.",
      "Editor de formularios: conserva con mayor fidelidad los cambios y el punto de trabajo al reabrir el proyecto.",
      "Carga y Gráficos: pulen la revisión de datos y los controles de configuración para reducir errores antes de procesar o exportar.",
    ],
  },
  {
    version: "0.2.8",
    date: "2026-05-25",
    highlights: [
      "Gráficos: estrena un configurador avanzado con una estructura más clara para cada tipo de lámina.",
      "Gráficos: agrega un editor visual de composición para ajustar el contenido dentro de la lámina.",
      "Gráficos: propone paletas y mejora el selector de color para mantener una identidad consistente.",
      "Gráficos: ordena la importación y exportación de configuraciones por secciones y valida mejor los valores numéricos.",
      "Procesamiento: moderniza Carga, Validación, Codificación y Analítica con una navegación más compacta y aprovechamiento completo de la pantalla.",
      "Codificación: evita que los grupos de respuestas queden cortados durante la revisión.",
    ],
  },
  {
    version: "0.2.7",
    date: "2026-05-22",
    highlights: [
      "Cálculo de muestra: estrena el módulo para diseñar muestras, comparar escenarios y generar reportes metodológicos.",
      "Enciclopedia: agrega fichas y catálogos de metodologías y tipos de estudio como apoyo para definir el diseño.",
      "Analítica: incorpora una revisión tabular de la base para inspeccionar los datos antes del análisis.",
      "Monitoreo: amplía el seguimiento del campo y su conexión con las fuentes del proyecto.",
      "Hojas de ruta: mejora la preparación territorial y los reportes de recorrido.",
      "Editor de formularios: refuerza la importación desde SurveyMonkey y los asistentes de reglas del instrumento.",
    ],
  },
  {
    version: "0.2.6",
    date: "2026-05-15",
    highlights: [
      "Actualización: muestra el contenido más reciente inmediatamente después de instalar una nueva versión.",
      "Actualización: evita que la aplicación reutilice pantallas de una versión anterior guardadas localmente.",
      "Escritorio: aplica la recarga segura tanto en Windows como en macOS.",
      "Arranque: abre la versión recién instalada sin exigir una limpieza manual de archivos temporales.",
    ],
  },
  {
    version: "0.2.5",
    date: "2026-05-15",
    highlights: [
      "Hojas de ruta: incorpora el marco oficial INEI 2017 con cartografía y nivel socioeconómico para preparar el trabajo territorial.",
      "Hojas de ruta: mejora el flujo operativo, la revisión de mapas y la organización de los recorridos.",
      "Monitoreo: agrega un tablero digital de campo compatible con fuentes Kobo y SurveyMonkey.",
      "Carga: valida que la base de datos corresponda al formulario antes de incorporarla al proyecto.",
      "Gráficos: reconstruye correctamente los íconos al exportar las láminas.",
    ],
  },
  {
    version: "0.2.4",
    date: "2026-05-10",
    highlights: [
      "Hojas de ruta: amplía la cartografía de calles y mejora la construcción de recorridos en Lima y Callao.",
      "Hojas de ruta: refuerza los filtros y la generación de salidas para equipos de campo.",
      "Editor de formularios: estrena un lienzo dedicado para editar preguntas, secciones y listas de opciones.",
      "Editor de formularios: agrega edición enriquecida, lógica visual y ayudas guiadas dentro del mismo espacio de trabajo.",
      "Inicio: unifica la navegación del proyecto y presenta con mayor claridad sus módulos y salidas.",
    ],
  },
  {
    version: "0.2.3",
    date: "2026-05-06",
    highlights: [
      "Instalación Windows: cierra de forma segura la aplicación antes de reinstalar una versión.",
      "Desinstalación Windows: libera el ejecutable antes de retirarlo para completar el proceso sin bloqueos.",
      "Actualización Windows: evita que una instancia abierta interrumpa el reemplazo de archivos.",
      "Escritorio: reduce la necesidad de cerrar procesos manualmente al mantener o retirar Prosecnur.",
    ],
  },
  {
    version: "0.2.2",
    date: "2026-05-06",
    highlights: [
      "Escritorio: captura los errores inesperados y muestra un mensaje que se puede copiar para solicitar soporte.",
      "Actualización: carga el actualizador de forma segura para que un fallo aislado no impida abrir la aplicación.",
      "Instalación Windows: incluye correctamente las dependencias necesarias dentro del paquete.",
      "Escritorio: estabiliza el arranque y el mantenimiento de la versión instalada en Windows y macOS.",
    ],
  },
  {
    version: "0.2.1",
    date: "2026-05-06",
    highlights: [
      "Instalación Windows: estrena un paquete autosuficiente con el motor estadístico incluido.",
      "Escritorio: asocia los archivos `.pulso` con Prosecnur para abrir proyectos directamente.",
      "Actualización: incorpora la descarga de nuevas versiones desde la aplicación instalada.",
      "Instalación macOS: agrega una imagen DMG con la identidad de Prosecnur.",
      "Hojas de ruta: incorpora el flujo cartográfico para preparar recorridos territoriales.",
      "Analítica y Gráficos: consolida mejoras de revisión y presentación en el primer corte instalable.",
    ],
  },
  {
    version: "0.14",
    date: "2026-05-03",
    highlights: [
      "Nuevo módulo Hojas de ruta: valida columnas de campo, arma cuotas por UMP, previsualiza mapas faltantes y genera un ZIP con PDFs listos para impresión.",
      "Editor XLSForm + SurveyMonkey: importación API-only más fiel, matrices y opciones “Otro” mejor interpretadas, lógica avanzada aplicable al formulario actual y nuevo asistente visual de saltos.",
      "Gráficos: inspector V2 reorganizado, controles visuales para colores por serie y criterios, presets Word sin JSON crudo, auto-layout/canvas más estable y leyendas configurables arriba/abajo/lados.",
      "Analítica: frecuencias y cruces ganan opciones para ocultar títulos/secciones, mejor manejo de categorías y select_multiple, filtros nombrados más robustos y UI de configuración más clara.",
      "Carga y normalización: aliases q→p, padding de opciones y reconstrucción de select_multiple se muestran en la vista previa; columnas extra quedan identificadas.",
      "Codificación y validación: textos abiertos independientes se pueden recodificar, la base adaptada alimenta Analítica automáticamente y las reglas/preview toleran mejor labels, fechas, regex y expresiones select_multiple.",
    ],
  },
  {
    version: "0.13",
    date: "2026-05-02",
    highlights: [
      "Independencia entre proyectos: fix de fuga de estado al cambiar de .pulso (Dashboard/Analítica/Gráficos/Wizard de Dimensiones se resetean al cambiar sid).",
      "StartModal rediseñado: solo Nuevo proyecto + Abrir proyecto + lista de Recientes con papelera (no borra el archivo, solo lo quita de la lista).",
      "Modo navegador desbloqueado: abrir/crear .pulso por path manual sin Electron.",
      "Editor de XLSForms: el export se guarda automáticamente en la carpeta del proyecto en vez de ~/Downloads.",
      "Home: grid de módulos 3×2 con sexto slot reservado.",
      "Fix Limpieza y normalización: el endpoint ya no se cae con E_INTERNAL al serializar evaluacion_final.",
      "Fix Codificación: preview de respuestas con un solo elemento ya no rompe la UI.",
      "Fix bootstrap: la app adopta el .pulso preload aunque jsonlite serialice NULL como `{}`.",
    ],
  },
  {
    version: "0.12",
    date: "2026-04-28",
    highlights: [
      "Dashboard exporta como HTML autosuficiente con WebR (R en el navegador, sin servidor).",
      "Bridge WebR para modo standalone: cómputo R nativo dentro del .html exportado.",
    ],
  },
  {
    version: "0.11",
    date: "2026-04-28",
    highlights: [
      "Dashboard: vista previa, paleta UI, recodificación por variable, override de vars.",
      "Revamp UX: toolbar afuera del canvas, marca con múltiples logos, sidebar Dimensiones rediseñado.",
      "Vista FODA Lectura como modo pedagógico.",
      "Avances en analítica/dimensiones, gráficos v2 y router del proyecto en R API.",
    ],
  },
  {
    version: "0.10",
    date: "2026-04-27",
    highlights: [
      "Dashboard fullscreen transversal, con skeleton de filtros y tests del semáforo.",
      "Barras h/v/facet, radar polygonal con modos/animado, FODA polish.",
      "Semáforo configurable, leyendas centradas, IterStepper, % fuera de barra.",
      "Chip rectangular al final de cada barra, FODA legacy preservado.",
      "Plotly como un solo chunk compartido (~4.6 MB) entre features.",
      "SessionChip resiliente a sessionId no-string + setter defensivo.",
    ],
  },
  {
    version: "0.9",
    date: "2026-04-26",
    highlights: [
      "Dashboard /tablero independiente, con paletas y reglas de diseño Emil aplicadas.",
      "Pestañas Relaciones y Base de datos con persistencia en el .pulso.",
      "Pestaña Dimensiones con heatmap semáforo, radar y barras.",
      "FODA scatter flotante + barras ordenadas con chip semáforo.",
      "Pasada de fidelidad al legacy reporte_interactivo.",
      "Curaduría preservada al reabrir un .pulso.",
    ],
  },
  {
    version: "0.8",
    date: "2026-04-21",
    highlights: [
      "Home rediseñado como menú de módulos — Prosecnur como suite multi-propósito.",
      "Notas de versión integradas con historial colapsable.",
      "Confirmación al cerrar la app para no perder progreso.",
    ],
  },
  {
    version: "0.7",
    date: "2026-04-20",
    highlights: [
      "Sistema de diseño unificado: tokens de status, primitivos compartidos, sin hex hardcoded en Fases 3/4/5.",
      "Color picker integrado en presets con paletas del estudio.",
      "Textos en negrita con multi-select de chips.",
      "Hot-reload del engine R sin reiniciar el proceso.",
    ],
  },
  {
    version: "0.6",
    date: "2026-04-18",
    highlights: [
      "Overrides defaults persistentes simétricos a presets defaults.",
      "DefaultsModal accesible desde el engranaje de Configuración global.",
    ],
  },
];
