#' Imports a nivel de paquete
#'
#' Bloque roxygen sin objeto asociado: existe solo para declarar los
#' `@importFrom` que usa todo el paquete y que ningún archivo reclama como
#' propios. El pipe de magrittr lo usan 13 archivos (`validacion_*`,
#' `codificacion_*`, `reporte_instrumento.R`) sin declararlo en su roxygen;
#' declararlo aquí es lo que hace que `roxygenise()` regenere
#' `importFrom(magrittr,"%>%")` en vez de borrarlo. Antes de este archivo esa
#' línea vivía editada a mano dentro del bloque «generated by roxygen2», y
#' cualquier regeneración la borraba y rompía los 324 usos de `%>%`.
#'
#' @importFrom magrittr %>%
#' @keywords internal
#' @noRd
NULL
