#!/usr/bin/env node
// Instrumento del loop de bóvedas (docs/plan-vaults-2026-07.md).
//
// Compara las bóvedas Obsidian contra la fuente única de navegación
// (`frontend/src/lib/modules.ts`) y contra el árbol real del repositorio.
// Mide y reporta; sólo `--generar` escribe el adaptador reproducible. El loop
// lo cierra una persona.
//
//   node scripts/vaults-check.mjs            informe legible
//   node scripts/vaults-check.mjs --check    sale 1 si hay deriva bloqueante
//   node scripts/vaults-check.mjs --json     informe serializado
//   node scripts/vaults-check.mjs --sellos   imprime el sello vigente por nodo
//   node scripts/vaults-check.mjs --generar  regenera docs/sistema/direcciones/
//
// La bóveda de producto es parte versionada del contrato documental. Su
// ausencia es un fallo: verde por conformidad, nunca por falta de cobertura.

import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { fileURLToPath, pathToFileURL } from 'node:url'

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const VAULT_PRODUCTO = path.join(REPO, 'Obsidian_Prosecnur')
const VAULT_SISTEMA = path.join(REPO, 'docs')
const FRONTEND = path.join(REPO, 'frontend')
const MANIFEST_AGENTIC = path.join(REPO, 'agentic', 'manifest.json')
const GENERATED = 'GENERATED BY scripts/vaults-check.mjs; DO NOT EDIT'

const ALIAS_PROHIBIDOS = ['tab', 'stage', 'mesa', 'desk', 'step', 'reporte']
const TIPOS_ESTRUCTURALES = ['indice', 'modulo', 'modo', 'seccion', 'pestana']

function normalizarTag(valor) {
  return String(valor ?? '').normalize('NFD').replace(/\p{Diacritic}/gu, '').toLowerCase()
}

const args = new Set(process.argv.slice(2))
const MODO_CHECK = args.has('--check')
const MODO_JSON = args.has('--json')
const MODO_SELLOS = args.has('--sellos')
const MODO_GENERAR = args.has('--generar')

// ---------------------------------------------------------------- contrato

/**
 * El contrato de navegación es TypeScript con imports de iconos: no se puede
 * `require`. Se carga con el Vite que ya vive en `frontend/node_modules`, que
 * es el mismo que compila la app — así el contrato medido es el que corre.
 */
async function cargarContrato() {
  const viteEntry = path.join(FRONTEND, 'node_modules', 'vite', 'dist', 'node', 'index.js')
  if (!fs.existsSync(viteEntry)) {
    throw new Error('falta frontend/node_modules/vite — corre `make install-frontend`')
  }
  const { createServer } = await import(pathToFileURL(viteEntry).href)
  const server = await createServer({
    root: FRONTEND,
    configFile: false,
    server: { middlewareMode: true, hmr: false, ws: false, watch: null },
    optimizeDeps: { noDiscovery: true },
    appType: 'custom',
    logLevel: 'error',
  })
  try {
    const mod = await server.ssrLoadModule('/src/lib/modules.ts')
    return mod.PROSECNUR_MODULES
  } finally {
    await server.close()
  }
}

/** Aplana el contrato a nodos direccionables: módulo, modo, sección, pestaña. */
function aplanarContrato(modulos) {
  const nodos = new Map()
  const registrar = (direccion, nodo) => nodos.set(direccion, nodo)

  for (const m of modulos) {
    const formaHijos = m.modos?.length
      ? m.modos.map((modo) => `${modo.id}:${modo.sections.map((seccion) => `${seccion.id}[${(seccion.tabs ?? []).map((tab) => tab.id).join(',')}]`).join(',')}`).join(';')
      : (m.sections ?? []).map((seccion) => `${seccion.id}[${(seccion.tabs ?? []).map((tab) => tab.id).join(',')}]`).join(';')
    registrar(`${m.slug}`, {
      tipo: 'modulo',
      modulo: m.slug,
      label: m.title,
      to: m.to ?? null,
      direccionPublicada: true,
      forma: [m.slug, m.title, m.to ?? '', m.landingKind, formaHijos].join('|'),
    })

    const bloques = m.modos?.length
      ? m.modos.map((mo) => ({ modo: mo.id, label: mo.label, sections: mo.sections }))
      : [{ modo: null, label: null, sections: m.sections ?? [] }]

    for (const bloque of bloques) {
      if (bloque.modo) {
        registrar(`${m.slug}/${bloque.modo}`, {
          tipo: 'modo',
          modulo: m.slug,
          modo: bloque.modo,
          label: bloque.label,
          direccionPublicada: true,
          forma: [m.slug, bloque.modo, bloque.label, bloque.sections.map((s) => s.id).join(',')].join('|'),
        })
      }
      for (const s of bloque.sections ?? []) {
        const base = bloque.modo ? `${m.slug}/${bloque.modo}` : m.slug
        registrar(`${base}/${s.id}`, {
          tipo: 'seccion',
          modulo: m.slug,
          modo: bloque.modo,
          seccion: s.id,
          label: s.label,
          to: s.to,
          direccionPublicada: true,
          forma: [m.slug, bloque.modo ?? '', s.id, s.label, s.to, (s.tabs ?? []).map((t) => t.id).join(',')].join('|'),
        })
        for (const t of s.tabs ?? []) {
          registrar(`${base}/${s.id}/${t.id}`, {
            tipo: 'pestana',
            modulo: m.slug,
            modo: bloque.modo,
            seccion: s.id,
            pestana: t.id,
            label: t.label,
            to: t.to,
            direccionPublicada: t.direccionPublicada !== false,
            forma: [
              m.slug,
              bloque.modo ?? '',
              s.id,
              t.id,
              t.label,
              t.to,
              t.direccionPublicada === false ? 'no-publicada' : 'publicada',
            ].join('|'),
          })
        }
      }
    }
  }

  const entradas = [...nodos.entries()]
  for (const [clave, nodo] of entradas) {
    // El sello de un contenedor protege su forma completa, no sólo los IDs de
    // sus hijos. Así un cambio de etiqueta, ruta o publicabilidad en cualquier
    // descendiente invalida también la revisión del módulo/modo/sección que lo
    // presenta.
    const formaCompleta = entradas
      .filter(([direccion]) => direccion === clave || direccion.startsWith(`${clave}/`))
      .map(([direccion, descendiente]) => `${direccion}:${descendiente.forma}`)
      .join('\n')
    nodo.sello = crypto.createHash('sha1').update(formaCompleta).digest('hex').slice(0, 8)
  }
  return nodos
}

/** Ruta de la app → clave de nodo. Devuelve también los alias que encontró. */
function direccionDesdeRutaApp(rutaApp, contrato) {
  const crudo = String(rutaApp ?? '').trim()
  if (!crudo) return { clave: null, alias: [], motivo: 'sin ruta_app' }

  const [pathname, query = ''] = crudo.split('?')
  const params = new URLSearchParams(query)
  const alias = ALIAS_PROHIBIDOS.filter((a) => params.has(a))

  // El módulo se resuelve por el `to` declarado en el contrato, no por tabla
  // aparte: si una ruta cambia en modules.ts, aquí cambia sola.
  let modulo = null
  for (const nodo of contrato.values()) {
    if (nodo.tipo === 'modulo' && nodo.to === pathname) modulo = nodo.modulo
  }
  if (!modulo) {
    // Rutas de sección con path propio (`/carga`, `/analitica`, …) se resuelven
    // contra el `to` de las secciones.
    for (const [claveSeccion, nodo] of contrato) {
      if (nodo.tipo !== 'seccion' || nodo.to !== pathname) continue
      const pestana = params.get('pestana')
      if (!pestana) return { clave: claveSeccion, alias, motivo: null }
      const clavePestana = `${claveSeccion}/${pestana}`
      if (contrato.get(clavePestana)?.direccionPublicada !== false && contrato.has(clavePestana)) {
        return { clave: clavePestana, alias, motivo: null }
      }
      if (contrato.has(clavePestana)) {
        return {
          clave: null,
          claveParcial: claveSeccion,
          alias,
          motivo: `la pestaña ${clavePestana} no publica dirección`,
          direccionNoPublicada: clavePestana,
        }
      }
      return { clave: null, claveParcial: claveSeccion, alias, motivo: `no resuelve: ${clavePestana}` }
    }
    return { clave: null, alias, motivo: `pathname desconocido: ${pathname}` }
  }

  const partes = [modulo]
  const modo = params.get('modo')
  const seccion = params.get('seccion')
  const pestana = params.get('pestana')
  if (modo) partes.push(modo)
  if (seccion) partes.push(seccion)
  if (pestana) partes.push(pestana)

  const clave = partes.join('/')
  if (contrato.get(clave)?.direccionPublicada !== false && contrato.has(clave)) {
    return { clave, alias, motivo: null }
  }
  if (contrato.has(clave)) {
    return {
      clave: null,
      claveParcial: partes.slice(0, -1).join('/'),
      alias,
      motivo: `la pestaña ${clave} no publica dirección`,
      direccionNoPublicada: clave,
    }
  }

  // Si falla sólo por la pestaña, la sección padre sigue siendo información
  // útil: distingue «la bóveda inventó una pantalla» de «el contrato no llega
  // hasta aquí».
  if (pestana) {
    const padre = partes.slice(0, -1).join('/')
    if (contrato.has(padre)) {
      return { clave: null, claveParcial: padre, alias, motivo: `no resuelve: ${clave}` }
    }
  }
  return { clave: null, alias, motivo: `no resuelve: ${clave}` }
}

// ------------------------------------------------------------------ bóveda

function recorrerMarkdown(dir, out = []) {
  if (!fs.existsSync(dir)) return out
  for (const entrada of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entrada.name.startsWith('.')) continue
    const full = path.join(dir, entrada.name)
    if (entrada.isDirectory()) recorrerMarkdown(full, out)
    else if (entrada.isFile() && entrada.name.endsWith('.md')) out.push(full)
  }
  return out
}

/** Frontmatter mínimo: escalares y listas. Sin dependencias. */
function leerFrontmatter(texto) {
  if (!texto.startsWith('---\n')) return null
  const fin = texto.indexOf('\n---', 3)
  if (fin === -1) return null
  const bloque = texto.slice(4, fin)
  const datos = {}
  let claveLista = null
  for (const linea of bloque.split('\n')) {
    const item = linea.match(/^\s+-\s+(.*)$/)
    if (item && claveLista) {
      datos[claveLista].push(item[1].trim().replace(/^["']|["']$/g, ''))
      continue
    }
    const par = linea.match(/^([A-Za-z_][\w-]*):\s*(.*)$/)
    if (!par) continue
    const [, clave, valor] = par
    if (valor.trim() === '' || valor.trim() === '[]') {
      datos[clave] = valor.trim() === '[]' ? [] : []
      claveLista = clave
    } else {
      datos[clave] = valor.trim().replace(/^["']|["']$/g, '')
      claveLista = null
    }
  }
  return datos
}

/**
 * Direcciones que un documento declara gobernar.
 *
 * La bóveda de producto lo dice en frontmatter porque sus notas nacieron con
 * él. La bóveda de sistema lo dice en una sección `## Gobierna` de prosa: son
 * 144 documentos escritos sin frontmatter y obligarlos a adoptarlo para
 * participar del puente convertiría una mejora incremental en una migración.
 */
function declaracionesGobierna(texto, fm) {
  const desdeFm = Array.isArray(fm?.gobierna) ? fm.gobierna : []
  // El cierre no puede usar `$`: con la bandera `m` casa al final de cada
  // línea y la captura se queda en la primera. `(?![\s\S])` es fin de entrada.
  const seccion = texto.match(/^##\s+Gobierna\s*\n([\s\S]*?)(?=\n##\s|(?![\s\S]))/m)
  if (!seccion) return desdeFm
  const desdeProsa = []
  for (const linea of seccion[1].split('\n')) {
    const item = linea.match(/^\s*[-*]\s+`([^`]+)`/)
    if (item) desdeProsa.push(item[1].trim())
  }
  return [...desdeFm, ...desdeProsa]
}

function cargarNotas(raiz) {
  if (!fs.existsSync(raiz)) return null
  return recorrerMarkdown(raiz).map((archivo) => {
    const texto = fs.readFileSync(archivo, 'utf8')
    const fm = leerFrontmatter(texto) ?? {}
    const rel = path.relative(REPO, archivo)
    const esAdr = rel.split(path.sep).slice(0, 2).join('/') === 'docs/adrs'
    const estadoAdr = esAdr ? texto.match(/^Estado:\s*(.+)$/m)?.[1]?.trim() ?? null : null
    return {
      archivo,
      rel,
      texto,
      fm,
      gobierna: declaracionesGobierna(texto, fm),
      autoridadVigente: !esAdr || estadoAdr === 'Aceptado',
      estadoAdr,
    }
  })
}

function cargarBocetos(raiz) {
  const dir = path.join(raiz, 'Bocetos')
  if (!fs.existsSync(dir)) return []
  return fs
    .readdirSync(dir)
    .filter((n) => n.endsWith('.canvas'))
    .map((n) => {
      const full = path.join(dir, n)
      try {
        return { rel: path.relative(REPO, full), canvas: JSON.parse(fs.readFileSync(full, 'utf8')) }
      } catch (error) {
        return { rel: path.relative(REPO, full), error: String(error.message) }
      }
    })
}

// ----------------------------------------------------------------- chequeos

function medir(contrato, notasProducto, notasSistema, bocetos) {
  const hallazgos = []
  const push = (codigo, gravedad, sujeto, detalle) => hallazgos.push({ codigo, gravedad, sujeto, detalle })

  const resumen = {
    nodosContrato: contrato.size,
    notasProducto: notasProducto?.length ?? null,
    notasSistema: notasSistema?.length ?? null,
    bocetos: bocetos.length,
  }

  if (!notasProducto) {
    push('V0', 'bloqueante', 'Obsidian_Prosecnur/', 'bóveda de producto ausente: la conformidad no es medible')
    return { hallazgos, resumen, cubiertos: new Set(), coberturaPorClave: new Map(), gobernadas: new Map() }
  }

  const cubiertos = new Set()
  const coberturaPorClave = new Map()

  for (const nota of notasProducto) {
    const { fm, rel } = nota
    const tipo = fm.tipo
    const historica = String(fm.historica ?? '').toLowerCase() === 'true'
    if (tipo && !TIPOS_ESTRUCTURALES.includes(tipo)) {
      push('V6', 'bloqueante', rel, `tipo fuera de la jerarquía: ${tipo}`)
    }
    if (tipo && historica) {
      push('V6', 'bloqueante', rel, 'una nota histórica no puede conservar tipo estructural')
    }
    if (!tipo) {
      if (!historica) {
        push('V6', 'bloqueante', rel, 'nota sin tipo estructural ni historica: true')
      } else {
        if ((fm.padres ?? []).length > 0) {
          push('V6', 'bloqueante', rel, 'nota histórica todavía enlaza padres estructurales')
        }
        const tags = Array.isArray(fm.tags) ? fm.tags : []
        const tagsEstructurales = new Set(['módulo', 'modulo', 'modo', 'seccion', 'sección', 'pestaña', 'pestana'])
        if (tags.some((tag) => tagsEstructurales.has(String(tag).toLowerCase()))) {
          push('V6', 'bloqueante', rel, 'nota histórica conserva un tag estructural')
        }
      }
      continue
    }
    if (tipo === 'indice') continue

    const tags = Array.isArray(fm.tags) ? fm.tags : []
    const esperado = normalizarTag(tipo)
    if (tags.length !== 1 || normalizarTag(tags[0]) !== esperado) {
      push('V6', 'bloqueante', rel, `tipo ${tipo} exige exactamente el tag estructural ${tipo}; recibió ${tags.join(', ') || 'ninguno'}`)
    }

    // V1/V2 — la dirección declarada resuelve y no usa alias antiguos.
    //
    // `nodo:` es la clave canónica y manda sobre `ruta_app`. Existe porque hay
    // módulos que todavía no publican su ubicación en la barra (ADR 0044
    // incumplido): ahí la URL colapsa cuarenta pantallas en una sola dirección
    // y sólo `nodo:` permite decir cuál es cuál.
    const porRuta = direccionDesdeRutaApp(fm.ruta_app, contrato)
    if (porRuta.alias.length) {
      push('V2', 'bloqueante', rel, `alias antiguos en ruta_app: ${porRuta.alias.join(', ')}`)
    }

    let clave = null
    if (fm.nodo) {
      if (contrato.has(fm.nodo)) {
        clave = fm.nodo
        const rutaCompatible = porRuta.clave
          && (porRuta.clave === fm.nodo || fm.nodo.startsWith(`${porRuta.clave}/`))
        if (!rutaCompatible) {
          push(
            'V1',
            'bloqueante',
            rel,
            `ruta_app "${fm.ruta_app ?? ''}" no resuelve al nodo ${fm.nodo} ni a uno de sus ancestros publicados: ${porRuta.motivo ?? porRuta.clave ?? 'sin resolución'}`,
          )
        }
      } else {
        push('V1', 'bloqueante', rel, `nodo declarado que no existe en el contrato: ${fm.nodo}`)
      }
      if (porRuta.direccionNoPublicada === fm.nodo) {
        push('V10', 'bloqueante', rel, `ruta_app inventa un deep-link que la app no publica: ${fm.ruta_app}`)
      }
    } else if (porRuta.clave) {
      const alcanzado = contrato.get(porRuta.clave)
      const nivelEsperado = TIPOS_ESTRUCTURALES.indexOf(tipo)
      const nivelAlcanzado = TIPOS_ESTRUCTURALES.indexOf(alcanzado.tipo)
      if (nivelAlcanzado < nivelEsperado) {
        // La URL sólo llega al módulo pero la nota documenta algo más hondo:
        // el módulo no publica dirección y la nota no declara `nodo:`.
        push('V8', 'bloqueante', rel, `documenta un ${tipo} pero su ruta sólo alcanza ${alcanzado.tipo} "${porRuta.clave}": falta el campo nodo:`)
      } else {
        clave = porRuta.clave
      }
    } else if (porRuta.claveParcial) {
      // La sección resuelve y la pestaña no: el contrato no llega a ese nivel.
      push('V1b', 'aviso', rel, `el contrato no declara la pestaña solicitada bajo ${porRuta.claveParcial}`)
    } else {
      push('V1', 'bloqueante', rel, `ruta_app "${fm.ruta_app ?? ''}" ${porRuta.motivo}`)
    }

    if (clave) {
      cubiertos.add(clave)
      if (!coberturaPorClave.has(clave)) coberturaPorClave.set(clave, [])
      coberturaPorClave.get(clave).push(nota)
      const nodo = contrato.get(clave)
      if (nodo.tipo !== tipo) {
        push('V7', 'aviso', rel, `declara tipo "${tipo}" y el contrato dice "${nodo.tipo}" en ${clave}`)
      }
      // V5 — `completa` sin sello vigente es una afirmación sin verificador.
      if (fm.documentacion === 'completa') {
        if (!fm.verificado_contra) {
          push('V5', 'bloqueante', rel, `"completa" sin verificado_contra (sello vigente: ${nodo.sello})`)
        } else if (fm.verificado_contra !== nodo.sello) {
          push('V5', 'bloqueante', rel, `sello caducado ${fm.verificado_contra} → ${nodo.sello}: el nodo cambió desde la última revisión`)
        }
      }
    }

    // V4 — las fuentes citadas siguen existiendo.
    for (const fuente of Array.isArray(fm.fuentes) ? fm.fuentes : []) {
      if (!fuente || fuente.startsWith('ruta/al/')) continue
      if (!fs.existsSync(path.join(REPO, fuente))) {
        push('V4', 'bloqueante', rel, `fuente inexistente: ${fuente}`)
      }
    }
  }

  for (const [clave, notas] of coberturaPorClave) {
    if (notas.length > 1) {
      push('V9', 'bloqueante', clave, `dirección reclamada por ${notas.length} notas: ${notas.map((nota) => nota.rel).join(', ')}`)
    }
  }

  // V3 — cobertura: nodos del contrato sin nota que los reclame.
  for (const [clave, nodo] of contrato) {
    if (!cubiertos.has(clave)) {
      push('V3', 'bloqueante', clave, `nodo ${nodo.tipo} "${nodo.label}" sin nota en la bóveda`)
    }
  }

  // B1 — puente: la bóveda de sistema declara qué direcciones gobierna.
  let conPuente = 0
  const gobernadas = new Map()
  for (const nota of notasSistema ?? []) {
    if (!nota.gobierna.length) continue
    conPuente += 1
    if (!nota.autoridadVigente) {
      push('B2', 'aviso', nota.rel, `declara gobierno sin autoridad vigente (Estado: ${nota.estadoAdr ?? 'desconocido'}); no cuenta en el puente`)
      continue
    }
    for (const direccion of nota.gobierna) {
      if (!contrato.has(direccion)) {
        push('B1', 'bloqueante', nota.rel, `gobierna una dirección que no existe: ${direccion}`)
        continue
      }
      if (!gobernadas.has(direccion)) gobernadas.set(direccion, [])
      gobernadas.get(direccion).push(nota.rel)
    }
  }
  resumen.notasSistemaConPuente = conPuente
  resumen.direccionesGobernadas = gobernadas.size

  // C1 — bocetos: un nodo puede anclarse a una dirección real con `direccion::`.
  let anclas = 0
  let anclasPromovidas = 0
  for (const boceto of bocetos) {
    if (boceto.error) {
      push('C1', 'bloqueante', boceto.rel, `canvas ilegible: ${boceto.error}`)
      continue
    }
    for (const nodo of boceto.canvas.nodes ?? []) {
      const promovida = /(?:^|\n)promovido::\s*(?:true|sí|si)(?:\n|$)/i.test(String(nodo.text ?? ''))
      for (const match of String(nodo.text ?? '').matchAll(/direccion::\s*([^\s\n]+)/g)) {
        anclas += 1
        if (!contrato.has(match[1])) {
          push('C1', 'bloqueante', boceto.rel, `ancla a una dirección inexistente: ${match[1]}`)
          continue
        }
        if (promovida) {
          anclasPromovidas += 1
          const notas = coberturaPorClave.get(match[1]) ?? []
          const notaVigente = notas.find((nota) => {
            const nodoContrato = contrato.get(match[1])
            return nota.fm.documentacion === 'completa' && nota.fm.verificado_contra === nodoContrato.sello
          })
          const autoridades = gobernadas.get(match[1]) ?? []
          if (!notaVigente || !autoridades.length) {
            const faltan = [
              !notaVigente ? 'nota completa con sello vigente' : null,
              !autoridades.length ? 'documento de sistema con autoridad vigente' : null,
            ].filter(Boolean)
            push('C3', 'bloqueante', boceto.rel, `promoción incompleta para ${match[1]}: falta ${faltan.join(' y ')}`)
          }
        }
      }
    }
  }
  resumen.anclasBoceto = anclas
  resumen.anclasPromovidas = anclasPromovidas
  if (!anclas) push('C0', 'bloqueante', 'Obsidian_Prosecnur/Bocetos/', 'no hay ninguna ancla direccion::; C1=0 sería verde por ausencia')
  if (!anclasPromovidas) push('C2', 'bloqueante', 'Obsidian_Prosecnur/Bocetos/', 'no hay ningún ejemplo marcado promovido:: true')

  return { hallazgos, resumen, cubiertos, coberturaPorClave, gobernadas }
}

function validarAgenticOs(contrato, resultado) {
  const push = (codigo, gravedad, sujeto, detalle) => resultado.hallazgos.push({ codigo, gravedad, sujeto, detalle })
  let manifest
  try {
    manifest = JSON.parse(fs.readFileSync(MANIFEST_AGENTIC, 'utf8'))
  } catch (error) {
    push('A0', 'bloqueante', 'agentic/manifest.json', `manifiesto ilegible: ${error.message}`)
    return
  }
  const documentation = manifest.documentation ?? {}
  const grupos = [
    ['skills', manifest.skills ?? [], documentation.skill_navigation_roots ?? {}, 'skills'],
    ['agentes', manifest.agents ?? [], documentation.agent_navigation_roots ?? {}, 'agentes'],
  ]
  let entradas = 0
  for (const [label, nombres, scopes, carpeta] of grupos) {
    for (const nombre of nombres) {
      entradas += 1
      if (!Object.hasOwn(scopes, nombre) || !Array.isArray(scopes[nombre])) {
        push('A1', 'bloqueante', `agentic/manifest.json#documentation.${carpeta}`, `${nombre} no declara raíces de navegación explícitas`)
        continue
      }
      for (const raiz of scopes[nombre]) {
        if (!contrato.has(raiz)) push('A1', 'bloqueante', `${label}/${nombre}`, `raíz que no existe en el contrato: ${raiz}`)
      }
      const nota = path.join(REPO, documentation.agentic_index_dir ?? '', carpeta, `${nombre}.md`)
      if (!fs.existsSync(nota) || !fs.readFileSync(nota, 'utf8').startsWith('<!-- GENERATED BY agentic/sync-agentic-os.mjs; DO NOT EDIT -->')) {
        push('A2', 'bloqueante', path.relative(REPO, nota), 'entrada agentic ausente o sin marca de generación')
      }
    }
  }
  for (const route of Object.keys(manifest.routes ?? {})) {
    const nota = path.join(REPO, documentation.agentic_index_dir ?? '', 'ramas', `${route}.md`)
    if (!fs.existsSync(nota) || !fs.readFileSync(nota, 'utf8').startsWith('<!-- GENERATED BY agentic/sync-agentic-os.mjs; DO NOT EDIT -->')) {
      push('A2', 'bloqueante', path.relative(REPO, nota), 'rama agentic ausente o sin marca de generación')
    }
  }
  resultado.resumen.entradasAgentic = entradas
  resultado.resumen.ramasAgentic = Object.keys(manifest.routes ?? {}).length
}

// ------------------------------------------------------------------ informe

function informar({ hallazgos, resumen }, contrato) {
  const porCodigo = new Map()
  for (const h of hallazgos) {
    if (!porCodigo.has(h.codigo)) porCodigo.set(h.codigo, [])
    porCodigo.get(h.codigo).push(h)
  }
  const titulos = {
    A0: 'manifiesto agentic ilegible',
    A1: 'alcance agentic fuera del contrato vivo',
    A2: 'entrada agentic generada ausente',
    V0: 'bóveda no medible',
    V1: 'dirección que no resuelve contra el contrato',
    V1b: 'el contrato no llega al nivel de pestaña',
    V2: 'alias de navegación antiguo en ruta_app',
    V3: 'nodo del contrato sin nota',
    V4: 'fuente citada que ya no existe',
    V5: '«completa» sin sello vigente',
    V6: 'tipo estructural ausente o fuera de la jerarquía',
    V7: 'tipo declarado distinto del contrato',
    V8: 'nota sin nodo: en un módulo que no publica dirección',
    V9: 'dirección reclamada por más de una nota',
    V10: 'ruta_app publica una pestaña que solo tiene nodo documental',
    B1: 'puente roto entre bóvedas',
    B2: 'declaración de gobierno sin autoridad vigente',
    C0: 'bocetos sin anclas verificables',
    C1: 'boceto anclado a una dirección inexistente',
    C2: 'ningún ejemplo de boceto promovido',
    C3: 'cadena promovida incompleta',
    G1: 'índice generado ausente o desactualizado',
  }

  console.log('Loop de bóvedas — estado medido\n')
  console.log(`  nodos del contrato vivo : ${resumen.nodosContrato}`)
  console.log(`  notas de producto       : ${resumen.notasProducto ?? 'no medible'}`)
  console.log(`  notas de sistema        : ${resumen.notasSistema ?? 'no medible'}`)
  console.log(`  notas con puente        : ${resumen.notasSistemaConPuente ?? 0}`)
  console.log(`  bocetos                 : ${resumen.bocetos}`)
  console.log(`  anclas / promovidas     : ${resumen.anclasBoceto ?? 0} / ${resumen.anclasPromovidas ?? 0}`)
  console.log(`  agentic entradas/ramas  : ${resumen.entradasAgentic ?? 0} / ${resumen.ramasAgentic ?? 0}\n`)

  const bloqueantes = hallazgos.filter((h) => h.gravedad === 'bloqueante').length
  for (const [codigo, lista] of [...porCodigo].sort()) {
    console.log(`${codigo} · ${titulos[codigo] ?? codigo} — ${lista.length}`)
    for (const h of lista.slice(0, 12)) console.log(`   ${h.sujeto}\n     ${h.detalle}`)
    if (lista.length > 12) console.log(`   … y ${lista.length - 12} más`)
    console.log()
  }

  if (MODO_SELLOS) {
    console.log('Sellos vigentes por nodo:\n')
    for (const [clave, nodo] of contrato) console.log(`  ${nodo.sello}  ${clave}`)
    console.log()
  }

  console.log(bloqueantes ? `Deriva bloqueante: ${bloqueantes} hallazgos.` : 'Sin deriva bloqueante.')
  return bloqueantes
}

// ----------------------------------------------------------------- generado

function construirIndiceDirecciones(contrato, { cubiertos, gobernadas }) {
  const destino = path.join(VAULT_SISTEMA, 'sistema', 'direcciones')
  const porModulo = new Map()
  for (const [clave, nodo] of contrato) {
    if (!porModulo.has(nodo.modulo)) porModulo.set(nodo.modulo, [])
    porModulo.get(nodo.modulo).push([clave, nodo])
  }

  const esperados = new Map()
  for (const [modulo, nodos] of porModulo) {
    const raiz = nodos.find(([, n]) => n.tipo === 'modulo')?.[1]
    const filas = nodos.map(([clave, nodo]) => {
      const docs = (gobernadas.get(clave) ?? []).map((rel) => {
        const desde = path.join(destino, 'x')
        return `[${path.basename(rel, '.md')}](${path.relative(path.dirname(desde), path.join(REPO, rel)).split(path.sep).join('/')})`
      })
      return `| \`${clave}\` | ${nodo.tipo} | ${nodo.label ?? '—'} | ${nodo.direccionPublicada ? 'sí' : 'no; usa \`nodo:\`'} | ${nodo.sello} | ${cubiertos.has(clave) ? 'sí' : '**no**'} | ${docs.join(', ') || '—'} |`
    })

    const cuerpo = [
      `<!-- ${GENERATED} -->`,
      '',
      `# Direcciones de ${raiz?.label ?? modulo}`,
      '',
      '> Documento generado por `scripts/vaults-check.mjs --generar`. No editar a mano:',
      '> la fuente es `frontend/src/lib/modules.ts` más las secciones `## Gobierna`',
      '> de la bóveda de sistema.',
      '',
      `Módulo \`${modulo}\`${raiz?.to ? ` · ruta \`${raiz.to}\`` : ''} · ${nodos.length} direcciones.`,
      '',
      '| Dirección | Tipo | Nombre visible | URL publicada | Sello | Documentada | Gobernada por |',
      '| --- | --- | --- | --- | --- | --- | --- |',
      ...filas,
      '',
    ].join('\n')

    esperados.set(path.join(destino, `${modulo}.md`), cuerpo)
  }

  const indice = [
    `<!-- ${GENERATED} -->`,
    '',
    '# Índice de direcciones',
    '',
    '> Documento generado por `scripts/vaults-check.mjs --generar`. No editar a mano.',
    '',
    'Cada dirección del contrato de navegación, con el documento que la gobierna',
    'y si la bóveda de producto la documenta. Es la costura entre las dos bóvedas:',
    'la de producto explica qué hace una pantalla, la de sistema por qué existe.',
    '',
    ...[...porModulo.keys()].map((m) => `- [${m}](${m}.md)`),
    '',
  ].join('\n')
  esperados.set(path.join(destino, 'README.md'), indice)
  return { destino, esperados }
}

function archivosMarkdownDirectos(dir) {
  if (!fs.existsSync(dir)) return []
  return fs.readdirSync(dir, { withFileTypes: true })
    .filter((entrada) => entrada.isFile() && entrada.name.endsWith('.md'))
    .map((entrada) => path.join(dir, entrada.name))
}

function esIndiceGenerado(archivo) {
  if (!fs.existsSync(archivo)) return false
  const texto = fs.readFileSync(archivo, 'utf8')
  return texto.startsWith(`<!-- ${GENERATED} -->\n`)
}

function validarIndiceDirecciones(indice, resultado) {
  const push = (sujeto, detalle) => resultado.hallazgos.push({ codigo: 'G1', gravedad: 'bloqueante', sujeto, detalle })
  for (const [archivo, esperado] of indice.esperados) {
    const rel = path.relative(REPO, archivo)
    if (!fs.existsSync(archivo)) push(rel, 'adaptador generado ausente; ejecuta `make vaults-index`')
    else if (fs.readFileSync(archivo, 'utf8') !== esperado) push(rel, 'adaptador generado desactualizado; ejecuta `make vaults-index`')
  }
  for (const archivo of archivosMarkdownDirectos(indice.destino)) {
    if (!indice.esperados.has(archivo)) push(path.relative(REPO, archivo), 'archivo extra dentro del directorio generado')
  }
}

function escrituraAtomica(archivo, contenido) {
  fs.mkdirSync(path.dirname(archivo), { recursive: true })
  const temporal = path.join(path.dirname(archivo), `.${path.basename(archivo)}.${process.pid}.${crypto.randomUUID()}.tmp`)
  try {
    fs.writeFileSync(temporal, contenido, 'utf8')
    fs.renameSync(temporal, archivo)
  } finally {
    if (fs.existsSync(temporal)) fs.unlinkSync(temporal)
  }
}

function generarIndiceDirecciones(indice) {
  for (const [archivo, contenido] of indice.esperados) {
    if (fs.existsSync(archivo) && fs.readFileSync(archivo, 'utf8') === contenido) continue
    if (fs.existsSync(archivo) && !esIndiceGenerado(archivo)) {
      throw new Error(`${path.relative(REPO, archivo)} colisiona con un archivo manual; se preservó`)
    }
    escrituraAtomica(archivo, contenido)
  }
  for (const archivo of archivosMarkdownDirectos(indice.destino)) {
    if (indice.esperados.has(archivo)) continue
    if (!esIndiceGenerado(archivo)) throw new Error(`${path.relative(REPO, archivo)} es manual; no se puede podar`)
    fs.unlinkSync(archivo)
  }
  return [...indice.esperados.keys()].map((archivo) => path.relative(REPO, archivo))
}

// --------------------------------------------------------------------- main

const modulos = await cargarContrato()
const contrato = aplanarContrato(modulos)
const notasProducto = cargarNotas(path.join(VAULT_PRODUCTO, 'Prosecnur'))
const notasSistema = cargarNotas(VAULT_SISTEMA)
const bocetos = cargarBocetos(VAULT_PRODUCTO)

const resultado = medir(contrato, notasProducto, notasSistema, bocetos)
validarAgenticOs(contrato, resultado)
const indiceDirecciones = construirIndiceDirecciones(contrato, resultado)
validarIndiceDirecciones(indiceDirecciones, resultado)
const bloqueantes = resultado.hallazgos.filter((hallazgo) => hallazgo.gravedad === 'bloqueante').length

if (MODO_GENERAR) {
  const escritos = generarIndiceDirecciones(indiceDirecciones)
  console.log(`Índice de direcciones regenerado — ${escritos.length} archivos:`)
  for (const rel of escritos) console.log(`  ${rel}`)
} else if (MODO_JSON) {
  console.log(
    JSON.stringify(
      {
        ...resultado,
        contrato: Object.fromEntries(
          [...contrato].map(([clave, nodo]) => [clave, {
            tipo: nodo.tipo,
            label: nodo.label,
            to: nodo.to ?? null,
            sello: nodo.sello,
            direccionPublicada: nodo.direccionPublicada,
          }]),
        ),
        cubiertos: [...resultado.cubiertos],
        coberturaPorClave: Object.fromEntries(
          [...resultado.coberturaPorClave].map(([clave, notas]) => [clave, notas.map((nota) => nota.rel)]),
        ),
        gobernadas: Object.fromEntries(resultado.gobernadas),
      },
      null,
      2,
    ),
  )
  if (MODO_CHECK && bloqueantes > 0) process.exit(1)
} else {
  informar(resultado, contrato)
  if (MODO_CHECK && bloqueantes > 0) process.exit(1)
}
